### ISSUE TITLE
[BUG] Fails to connect if multiple wallets installed on browser (Metamask + Core)

### ISSUE THREAD

**Issue by ItsMeTazz** [family/connectkit#112]
**Describe the bug**

Not sure if that's a bug or a missing configuration, but I've always used Metamask with no issues. Today, while trying to use another wallet (Core), it seems like I can't connect to my local dapp anymore if I have more than 1 wallet installed on my browser. 
Browser gives me the following error: 
```
ConnectorNotFoundError: Connector not found
    at MetaMaskConnector.connect (wagmi-core-connectors-metaMask.esm.js?b785:65:1)
    at async connect (wagmi-core.esm.js?eef1:1308:1)
```
Same behavior on https://docs.family.co/connectkit/try-it-out, so I guess ConnectKit doesn't support Core yet?
When I try to update connectkit to its latest version, my project won't start anymore with the following error: 
```
Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at ConnectKitProvider (file:///......../node_modules/connectkit/build/index.es.js:8502:48)
```

**To reproduce**

With connectkit": "^0.0.2", simply install Core wallet (https://core.app/?lang=en-US) and try to connect to dapp with it. 

**Expected behavior**

A successful connection.

**Screenshots**

![image](https://user-images.githubusercontent.com/104685150/217042053-c99fc54e-b842-4620-963f-d14246618978.png)

**Environment details**

Windows, Chrome Version 109.0.5414.120 (Official Build) (64-bit)

Thanks!

**Comment by lochie** [comment]
@ItsMeTazz Does this issue also occur on the wagmi example? some injected connectors try to mimic metamask instead of using their own provider and override some behaviours which is difficult to cater to.
https://wagmi.sh/examples/connect-wallet

**Comment by lochie** [comment]
When injected providers override metamask this causes conflict errors, not something we can control sadly.

**Comment by ItsMeTazz** [comment]
Apologies for the late response but yes, also happens with the default example of connectkit.
