### ISSUE TITLE
[BUG] Modal open causes padding to get added to <body>

### ISSUE THREAD

**Issue by allenchuang** [family/connectkit#120]
**Describe the bug**

On click of modal open,  `<body>` gets added `overflow: hidden; position: relative; touch-action: none; padding-right: 15px;`, which causes a visual shift in screen.

**Expected behavior**

Body should not get added `padding-right: 15px`

**Comment by lochie** [comment]
@allenchuang you can turn this off by using the `avoidLayoutShift` option on your `ConnectKitProvider` 

[https://docs.family.co/connectkit/api-reference#ConnectKitProvider-avoidLayoutShift](https://docs.family.co/connectkit/api-reference#ConnectKitProvider-avoidLayoutShift)
