### ISSUE TITLE
[BUG] Can not use Celo, with a custom wagmi client

### ISSUE THREAD

**Issue by 0xGedo** [family/connectkit#126]
**Describe the bug**

The documentation mentions that connectkit usese wagmi internally, meaning all the various chains from wagmi are available. However when using a custom wagmi client with Celo imported from wagmi, the modal displays a message saying the chain is unsupported.

**To reproduce**

**Connectkit**:1.1.3

A CodeSandbox (preferably) or specify which version of ConnectKit you're using along with reproduction steps.

**Expected behavior**

**Screenshots**

![image](https://user-images.githubusercontent.com/110882071/219557031-29842a83-9a7c-47de-a3c7-af7373a0e01d.png)

**Environment details**

If applicable, let us know which OS, browser, browser version etc you're using.

**Additional context**

Adding Celo to the array of supported chains should allow the connection.

**Comment by lochie** [comment]
Hey @0xGedo, I've tested this and it looks like `celo` shows up fine if setting this up in your `WagmiConfig`, though we have yet to include logos for our UI, it should still function perfectly fine.

<img width="338" alt="CleanShot —02-20 at 22 43 13@2x" src="https://user-images.githubusercontent.com/1930210/220097175-a8caa94d-185f-4af9-942c-72a22d0b49e3.png">

Could you share your `createClient` configuration so we can help debug?

**Comment by 0xGedo** [comment]
@lochie thanks for testing and looking into this. It seems like this was an issue on my end, when I passed in an infura API key i was getting an error. But removing it seems to work fine and the client uses forno. This issue can be closed 🙏
