### ISSUE TITLE
[BUG] Getting error if I use Wagmi createClient rather than Connectkits getDefaultClient

### ISSUE THREAD

**Issue by launchthatbrand** [family/connectkit#133]
**Describe the bug**

I am able to setup connectkit using the basic getDefaultClient method. When swapping for the more robust Wagmi client I am getting an error:

"TypeError: Cannot read properties of undefined (reading '0'"

It says in the documentation:

"then create a client using either wagmi's createClient method or the pre-configured getDefaultClient ConnectKit provides."

Also in the advanced connectkit documenttion there is an example without getDefaultClient:
https://docs.family.co/connectkit/providers#custom-providers-example

I copied this and am still getting the error.

<img width="1152" alt="image" src="https://user-images.githubusercontent.com/70350889/220959872-24c92cf6-3d62-4370-8972-96ff663f35f6.png">

**Environment details**

Next 13
I have tried Connectkit v 1.0.0 and  v1.1.4

**Comment by 70nyIT** [comment]
Same error here

**Comment by Kinco-dev** [comment]
Same error here.
I'll wait the merge, thanks @lochie :)

**Comment by traumaxp** [comment]
Same here... waiting merge...

**Comment by lochie** [comment]
This should be resolved in ConnectKit version `1.2.1` with wagmi `0.11.x`.
If you're still seeing this issue please let us know. A reproducable codesandbox would also be incredibly helpful for us to debug further if necessary!
