### ISSUE TITLE
[BUG] SIWE Example with Next.js not working 

### ISSUE THREAD

**Issue by stackaccount1** [family/connectkit#142]
**Describe the bug**

The new SIWE Next.js implementation does not appear to be working properly, 

**To reproduce**

[A CodeSandbox Example Of My Problem](https://codesandbox.io/p/sandbox/connectkit-nextjs-typescript-forked-vcdvxk?file=%2Fpages%2FtokenGatedPage.ts&selection=%5B%7B%22endColumn%22%3A4%2C%22endLineNumber%22%3A18%2C%22startColumn%22%3A4%2C%22startLineNumber%22%3A18%7D%5D)

**Expected behavior**

If siweClient.Provider is removed this works properly. When added there are problems.  I have been following the new documentation from **https://docs.family.co/connectkit/auth-with-nextjs#siwe-nextjs-implementation-1-install**

**Screenshots**

![error](https://user-images.githubusercontent.com/61128114/222237181-f02e0573-e2a2-4e60-8e4d-d141e824c699.png)

**Additional context**

It is possible I have the wrong dependencies, if so please specify them somewhere on the documentation. Thank you. 

A full SIWE/Next.js/connectkit code example would be very helpful if possible :)  Thank you.

**Comment by lochie** [comment]
hey @stackaccount1, assuming you copy and pasted this from the docs, so you need to replace `void` with your choice of function, as `void` is a type definition and not a function.

Since these are just the defaults, you can remove these optional parameters if you wish and just use `<siweClient.Provider>` without any options.

**Comment by stackaccount1** [comment]
> hey @stackaccount1, assuming you copy and pasted this from the docs, so you need to replace `void` with your choice of function if you wish to use these features, as `void` is a type definition and not a function.
> 
> Since these are just the defaults, you can remove these optional parameters if you wish and just use `<siweClient.Provider>` without any options.

Thank you!
