### ISSUE TITLE
[BUG] Connect To Network Always Triggers Switch Network to Ethereum

### ISSUE THREAD

**Issue by joeblau** [family/connectkit#16]
**Describe the bug**

If you click connect wallet and you're not on Ethereum, you will always get prompted to switch to Ethereum even if the other network is approved.

**To reproduce**

1. Go to https://docs.family.co/connectkit/try-it-out
2. Switch to Goreli
3. Click "Connect Wallet" (It usually works the first time)
4. Approve Metamask prompts
5. Click "Disconnect"
6. Click "Connect Wallet"
7. Approve Connected account
8. ‼️ You will see Metamask prompt asking you to switch to Ethereum

**Expected behavior**

I would expect the connect button to connect to the site without forcing the user to Ethereum every single time.

**Screenshots**

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/1218847/193443188-c4618465-7054-4d5a-b8e4-f0f0025a58e4.png">

**Comment by lochie** [comment]
Hey @joeblau,

This is [intended behaviour that we introduced](https://github.com/family/connectkit/releases/tag/v0.0.2) in `0.0.2` to prevent users connecting to a network that the dApp does not support so we can avoid the `Wrong Network` state after connecting.

> The requested chain during connection now automatically targets the first chain in the developer’s client configuration.

The examples in the docs are set up with the chain configuration of `[chain.mainnet, chain.polygon, chain.optimism, chain.arbitrum]`, which is why it requests the switch to Ethereum Mainnet (first chain in the list).

It sounds like this behaviour isn't something that all developers might want, so we'll look into adding the option to turn this on/off in a future release.

**Comment by joeblau** [comment]
Ah okay! Yeah I would expect to to allow you to switch to any chain in the list and not force you to the first chain on the list.

thanks for the follow up!

**Comment by GeraldHost** [comment]
@joeblau even though that demo is setup with those networks it still tries to connect to the first chain on the list. For example if I am connected to polygon in metamask and click "Connect" it will trigger a switch network from polygon to mainnet. This seems like it is a bug? 

Also agree it would be good to have the "not force" to be a configurable options. 🖖

**Comment by GeraldHost** [comment]
@lochie  even though that demo is setup with those networks it still tries to connect to the first chain on the list. For example if I am connected to polygon in metamask and click "Connect" it will trigger a switch network from polygon to mainnet. This seems like it is a bug?

Also agree it would be good to have the "not force" to be a configurable options. 🖖

**Comment by lochie** [comment]
@GeraldHost The codebase currently targets the first chain in the list on connect.
https://github.com/family/connectkit/blob/bb746f308f71252fe64e3a92f648ebe650300640/packages/connectkit/src/hooks/useConnect.tsx#L20

I have been having some talks internally with our UX designers at Family about the best way to avoid an incorrect network connection and give everyone access to pick the default chain to connect to.
I should have an update for you within the next day or two.

**Comment by lochie** [comment]
I don't think that it's possible to do that first suggestion as that line of code is for the actual wallet connection request, rather than a post-connection change network request.

But exactly what you're suggesting for dev options is what we had in mind, hopefully can get an update with this out this week. ✨

**Comment by GeraldHost** [comment]
@lochie any update on this? 😇

**Comment by lochie** [comment]
Hey everyone!

We just dropped a [new version of ConnectKit](https://github.com/family/connectkit/releases/tag/v1.0.0) that has an updated UX flow for unsupported chains which prompts the user to change to a supported network. 

We also have a [new parameter](https://docs.family.co/connectkit/api-reference#ConnectKitProvider-initialChainId) (`initialChainId`) where you can choose the preferred chain to connect to from your supported chains.

I hope this solves all the above suggestions!
cc @joeblau @shixin-guo @GeraldHost

**Comment by dirtycajunrice** [comment]
> Hey everyone!
> 
> We just dropped a [new version of ConnectKit](https://github.com/family/connectkit/releases/tag/v1.0.0) that has an updated UX flow for unsupported chains which prompts the user to change to a supported network.
> 
> We also have a [new parameter](https://docs.family.co/connectkit/api-reference#ConnectKitProvider-initialChainId) (`initialChainId`) where you can choose the preferred chain to connect to from your supported chains.
> 
> I hope this solves all the above suggestions! cc @joeblau @shixin-guo @GeraldHost

While this IS an improvement, I would not consider this to be closed/complete. This only solves for half of the issue.
Configurable default chain should be looked at solely as a **fallback** when the currently connected chainId is out of the supported networks.
Multi-chain applications are far and wide, and the user experience of being on chain B, being asked to switch to chain C, only to have to switch back to chain B is not a good one.

I understand that certain connectors (like walletconnect)  do not support switching, and that it may seem “easier” on the surface to unilaterally code with that in mind, but injected wallets are the majority, not the minority. With that in mind, wallet connection and network selection should be separate.

**Comment by rsodre** [comment]
First, congrats to this incredible plugin, it was super easy to set up and expand my user base.

But @lochie, I don't think this update addresses the original problem, I'm having the same issue now that I added ConnectKit to my current Metamask-only wagmi dapp.

My chains are `[mainnet, goerli]`, Metamask is already connected to Goerli, and ConnectKit always asks me to connect to Mainnet every time. I am already on a supported chain, it should just accept that.

Or how am I supposed to connect to Goerli if I need to? By manually switching `initialChainId`? Do I need two environments? Stop the server, change env and starting it again? Adding a dropdown on the dapp to select the chain I want?

All those workflows sound really dumb and time-consuming. Please enlighten me on what I need to do to connect to the **already connected and supported network**, I don't get it.

**Comment by lochie** [comment]
> @rsodre: what I need to do to connect to the already connected and supported network

It's a little complicated with how this works as we can't tell what chain a user is connecting with, but we have the option to target a chain. To help solve this issue we've released an update in ConnectKit `1.1.2` where if you set the [`initialChainId` to `0`](https://docs.family.co/connectkit/api-reference#ConnectKitProvider-initialChainId) it will no longer target a chain and let the wallet connect to whichever chain it was previously set to.

Hopefully this update also fixes other issues described in this thread.

**Comment by Songkeys** [comment]
Even i set initialChainId to 0, this switch network modal still pops up:

<img width="337" alt="image" src="https://user-images.githubusercontent.com/22665058/220587064-ceeb262a-b1e1-4cb2-afff-e468e3204607.png">

Is there anyway to avoid this?

**Comment by lochie** [comment]
@Songkeys just had some time and quickly looked into this, would this PR solve this problem? https://github.com/family/connectkit/pull/129
