### ISSUE TITLE
[BUG] Modal does not close after connecting wallet, if opened with setOpen

### ISSUE THREAD

**Issue by Jeremy-Park** [family/connectkit#160]
**Describe the bug**

After using `setOpen` to programatically open modal, modal no longer closes upon connecting wallet.

**To reproduce**

- ConnectKit version 1.2.1
- Use `setOpen` to open the modal
- Connect a wallet (I used coinbase wallet)
- Say yes to everything and wallet has been connected
- Wallet address shows in the `<ConnectKitButton />`
- Modal hangs, and stays open

**Expected behavior**

- Using `setOpen` to open the modal should behave just like clicking on `<ConnectKitButton />`
- Use `setOpen` to open the modal
- Connect a wallet
- Wallet connected
- Modal closes upon wallet connection

**Screenshots**

![image](https://user-images.githubusercontent.com/32861944/225250587-11795c18-fd23-434f-91f6-00102eeebafd.png)
As you can see in the screenshot, I have connected my wallet and the modal still stays open

**Environment details**

Latest chrome
Windows 10 \ latest macOS
On localhost and also on deployed versions of the website

**Additional context**

This also triggers another little bug. If you can get this to happen, try disconnecting. Then click connect again. The modal will open for a fraction of a second and close. If you click again, modal will open normally.

**Comment by lochie** [comment]
hey @Jeremy-Park, do you have an example where I can test this? I'm unable to reproduce in our testing environments

**Comment by lochie** [comment]
mb accidentally closed-with-comment instead of just comment 😅

**Comment by ZiyongHe** [comment]
I am working on the same project and trying to debug it. This issue won't occur in an isolated case, outside our project scope. So we cannot provide an example code for you to reproduce. Let me provide you with more details of what we see.

**Comment by ZiyongHe** [comment]
We have resolved the issue.

Caused by including the following code inside the MyApp react function, while they should be outside the MyApp react function.

`
  const chains = [mainnet, goerli, bsc, bscTestnet, polygon, fantom, avalanche]
  const client = createClient(
    getDefaultClient({ appName: 'xxx', chains }),
  );
  `

**Comment by lochie** [comment]
Nice @ZiyongHe, that's great to know for if anyone else has a similar issue. Thanks!
