### ISSUE TITLE
[BUG] WalletConnect key being console logged in browser

### ISSUE THREAD

**Issue by daedboi** [family/connectkit#167]
**Describe the bug**

Developing a dApp on Fantom where infura / alchemy are not available, and whenever opening the WalletConnect qr modal, the console logs the bridge/key uri, which could potentially be abused.

**To reproduce**

Using the latest version of ConnectKit (v1.2.1), if opening the qr modal it will console.log the uri. I've tried using the defaultClient from ConnectKit as well as a custom wagmi client configuration, present everywhere.

**Expected behavior**

I am expecting the WalletConnect qr modal to not console log the connection uri.

**Screenshots**

![image](https://user-images.githubusercontent.com/87483308/226709562-d3000574-89c3-4183-80b2-bbddbd98fdac.png)

**Environment details**

Chrome

**Additional context**

**Comment by daedboi** [comment]
Issue seems to stem from here:
https://github.com/family/connectkit/blob/97a0bb64e314a0dcc13c579d6f84ff91e832bee9/packages/connectkit/src/components/ConnectModal/ConnectWithQRCode.tsx#L77

And possibly here:
https://github.com/family/connectkit/blob/97a0bb64e314a0dcc13c579d6f84ff91e832bee9/packages/connectkit/src/components/Pages/MobileConnectors/index.tsx#L92

**Comment by lochie** [comment]
This log comes from WalletConnect V1's SDK and can be replicated in their example: https://example.walletconnect.org/
Also worth noting that we are introducing a `debugMode` flag which shows/hides ConnectKit console logs overall.
