### ISSUE TITLE
always ask switch network to mainnet

### ISSUE THREAD

**Issue by shixin-guo** [family/connectkit#17]
### Discussed in https://github.com/family/connectkit/discussions/10

<div type='discussions-op-text'>

<sup>Originally posted by **shixin-guo** September 29, 2022</sup>
<img width="365" alt="image" src="https://user-images.githubusercontent.com/12186221/192903614-da2cd6e3-b0c6-4822-bcb0-d299dc8b7d9b.png">

When I connect with MetaMask after upgrading to 0.0.2, connectKit asks me to switch to Mainnet, but I want to use Rinkeby TestNet. Do you know what's causing this?

Because 0.0.1 is working properly, I am perplexed.😢 

this is my test code
```
import { ConnectKitProvider } from 'connectkit'
import {
  WagmiConfig,
  createClient,
  allChains,
  configureChains,
  chain,
} from 'wagmi'

import { publicProvider } from 'wagmi/providers/public'

import { CoinbaseWalletConnector } from 'wagmi/connectors/coinbaseWallet'
import { MetaMaskConnector } from 'wagmi/connectors/metaMask'
import { InjectedConnector } from 'wagmi/connectors/injected'
import { WalletConnectConnector } from 'wagmi/connectors/walletConnect'

import { firebaseApp } from '@framework/provider'

const { chains, provider, webSocketProvider } = configureChains(allChains, [
  publicProvider(),
])
const client = createClient({
  autoConnect: true,
  connectors: [
    new MetaMaskConnector(),
    new InjectedConnector({ chains: [chain.hardhat] }),
    new CoinbaseWalletConnector({
      chains,
      options: {
        appName: 'wagmi',
      },
    }),
    new WalletConnectConnector({
      chains,
      options: {
        qrcode: true,
      },
    }),
  ],
  provider,
  webSocketProvider,
})
```</div>

**Comment by shixin-guo** [comment]
same issue https://github.com/family/connectkit/issues/16

**Comment by lochie** [comment]
Just to answer the secondary question in this issue, in `0.0.2` we [introduced the change](https://github.com/family/connectkit/releases/tag/v0.0.2) that causes this automatic targeting.
> The requested chain during connection now automatically targets the first chain in the developer’s client configuration.

**Comment by lochie** [comment]
An [update is available](https://github.com/family/connectkit/issues/16#issuecomment-1306543682) in version `1.0.0` that allows some customisation for the above @shixin-guo

**Comment by mdl** [comment]
> 

what if I want to have default chain that is currently selected in metamask (or other wallet) in case it is in the list of supported chains?
