### ISSUE TITLE
[BUG] WalletConnect Not Working Correctly

### ISSUE THREAD

**Issue by ian** [family/connectkit#181]
**Describe the bug**

For some reason, WalletConnect is not working on a rather vanilla installation. Both Metamask and Coinbase wallet are working perfectly out of box.

The Wallet Connect modal pops behind the connectkit modal.

**To reproduce**

connectkit@1.2.1
ethers@^5.6.8
wagmi@0.12.7

**Expected behavior**

On the connectkit docs, the wallet connect shows a QR code and the user is able to connect.

**Screenshots**

![2023-03-31 12 52 46](https://user-images.githubusercontent.com/19853/229194442-6c12860e-b562-46db-8bf2-d1325fcc9d62.gif)

**Environment details**

Brave / MacOS

**Additional context**

Here's a code sample:

```
const { provider, webSocketProvider, chains } = configureChains(
  [goerli],
  [
    alchemyProvider({
      apiKey: process.env.NEXT_PUBLIC_ALCHEMY_KEY as string,
    }),
  ]
);

const client = createClient({
  autoConnect: true,
  connectors: [
    new WalletConnectConnector({
      chains,
      options: {
        qrcode: true,
        projectId: "MY PROJECT ID",
      },
    }),
  ],
  provider,
  webSocketProvider,
});

export default function App({ Component, pageProps }: AppProps) {
  return (
    <WagmiConfig client={client}>
      <ConnectKitProvider><Component {...pageProps} /></ConnectKitProvider>
    </WagmiConfig>
  );
}

```

**Comment by lochie** [comment]
You'll need to switch `qrcode: true` to `showQrModal: false`, as `qrcode` is not a valid option in that version of wagmi, and you'll want to set this as `false` to stop that modal from auto-launching.
https://wagmi.sh/react/connectors/walletConnect#showqrmodal-optional

In saying that, although it is functional, we're still working on full support for WalletConnect's 2.0 connector. If you want a better experience you'll need to opt for the `WalletConnectLegacyConnector` for the time being until we have a `1.3.0` update which fully supports the latest connector.

You can read more here: https://wagmi.sh/react/connectors/walletConnectLegacy
