### ISSUE TITLE
Mobile browser debugging demo, unable to connect to wallet

### ISSUE THREAD

**Issue by Autumn-Rains-yan** [family/connectkit#187]
connectkit version: `1.2.2`
I tried nextjs and vite, built the environment locally, and ran it on Android Google Browser

1: tap Connect Wallet.
2: tap MetaMask,Called up Metamask Dapp.
3: After entering Metamask, sometimes there is no response at all, and sometimes the following prompts appear in Metamask.
![1680586792852](https://user-images.githubusercontent.com/41866020/229698600-813a42b6-ac3e-4c66-9a5b-ce3100d6f7b7.jpg)
[https://docs.family.co/connectkit/try-it-out](https://github.com/family/connectkit/discussions/url)
The example in the document can be connected to a wallet

**Comment by sjunaiduk** [comment]
Are you using Metamask on Chrome? The recent update has caused bugs with Metamask.
https://github.com/MetaMask/metamask-extension/issues/18453

**Comment by lochie** [comment]
Thanks for letting us know about that @sjunaiduk!
Closing this issue as this is a bug with MetaMask and not ConnectKit.
