### ISSUE TITLE
[BUG] Blur effect on modal text

### ISSUE THREAD

**Issue by shankiflang** [family/connectkit#192]
**Describe the bug**

Hi,

I don't understand why but on all sites using connectKit I see blurred modals.

**Screenshots**

No blur (This image is modified)
![image](https://user-images.githubusercontent.com/32774804/230416325-cb18f58f-68c2-48f3-88eb-30199766f509.png)

What I see everywhere 
![image](https://user-images.githubusercontent.com/32774804/230416377-1fb16b09-3a8b-44f6-b74c-100c321a1182.png)

**Comment by lochie** [comment]
Hey @shankiflang, this has to do with css transforms for animation, and is a cross between monitor pixel density and browser render engines causing this issue and unfortunately is not something we can control easily on our end without removing all the animations entirely from the modal. Our team is [looking at some performance refactoring](https://github.com/family/connectkit/tree/djin/refactor-animation) which may help resolve this issue, but it's not something that is planned on our roadmap.
