### ISSUE TITLE
[BUG] - built in network switch modal doesn't properly handle network switching

### ISSUE THREAD

**Issue by cryptod00c** [family/connectkit#193]
**Describe the bug**

1. Use the examples/nextjs folder
2. Connect Wallet
3. Attempt to Switch Networks off of Ethereum (I'd bet this works for other networks as well)

**To reproduce**

A CodeSandbox (preferably) or specify which version of ConnectKit you're using along with reproduction steps.

**Expected behavior**

That the built in chain switch modal properly switches network

**Screenshots**

inpage.js:1 MetaMask - RPC Error: networkConfigurationId undefined does not match a configured networkConfiguration Object
(anonymous) @ inpage.js:1

next-dev.js:20 SwitchChainError: Error switching chain
    at MetaMaskConnector.switchChain

**Environment details**

mac, chrome, examples/nextjs folder

**Additional context**

Love that you made the switch modal hook available, I'll use this instead of my homegrown solution, just want it work :)

**Comment by Maurechi** [comment]
Same here. It could be something with wagmi cause their useSwitchNetwork hook also doesn't work

**Comment by Maurechi** [comment]
altho upgrading wagmi dependency breaks other things `Error: WebSocket connection failed for URL: wss://relay.walletconnect.com?`

**Comment by Maurechi** [comment]
Was having the same issue. It happens only with Metamask. Switching chains works with other wallets.

**Comment by D1scoDancer** [comment]
Same thing. Do you have any plans to address this issue in the near future?

**Comment by lochie** [comment]
Looks like a recent update to MetaMask has caused this issue.
https://github.com/MetaMask/metamask-extension/issues/18453

This will be fixed when MetaMask pushes an update on their end.
