### ISSUE TITLE
[BUG] "showBalance" is absent in ConnectKitProvider options

### ISSUE THREAD

**Issue by a35026** [family/connectkit#195]
**Describe the bug**

Unable to find a way to show the balance with the Custom ConnectKitButton  
According to the documentation: https://docs.family.co/connectkit/api-reference#showBalance

**To reproduce**
```tsx
<ConnectKitProvider
  options={{
    // showBalance property not found
  }}
>
  <ConnectKitButton.Custom>
    {({
      isConnected,
      truncatedAddress,
      isConnecting,
      show,
      hide,
      address,
      ensName,
      chain,
      unsupported,
      // no other properties available
    }) => {
      return (
        <button onClick={show}>
          // custom button
        </button>
      );
    }}
  </ConnectKitButton.Custom>
</ConnectKitProvider>
```

**Screenshots**

![image](https://user-images.githubusercontent.com/66538710/231241007-b536470b-f6e1-4de3-bb63-a54a261d6561.png)

**Environment details**

Google Chrome on MacOS Ventura

**Additional context**

Connectkit version: 1.2.2

**Comment by lochie** [comment]
you can use wagmi's `useBalance` hook to achieve this

https://wagmi.sh/react/hooks/useBalance
