### ISSUE TITLE
[BUG] ConnectButtonRenderer's isConnecting is false if modal is closed but still connecting

### ISSUE THREAD

**Issue by ryanberckmans** [family/connectkit#203]
Right now, ConnectButtonRenderer's isConnecting is true only if the modal is open. But, the modal can be closed while still connecting. So isConnecting==false while modal is closed and we're connecting.

Fixed by https://github.com/family/connectkit/pull/202

**Comment by ryanberckmans** [comment]
I had to close #202, possibly due to a bug in wagmi. See PR thread for details

**Comment by lochie** [comment]
I believe there have been some updates to help resolve this in the latest version (`1.4.0`). If it's still not acting as you expect feel free to reopen and explain further. Thanks!
