### ISSUE TITLE
Mobile wallets are not supported and dont get opened on iOS/android

### ISSUE THREAD

**Issue by duckdegen** [family/connectkit#208]
**Describe the bug**

Unable to connect using mobile devices, both iOS and Android.

**To reproduce**

Use a mobile browser and attempt connecting a wallet

**Expected behavior**

My wallet opens and prompts for connection

**Environment details**

Android latest, ios latest, using chrome latest

**Comment by lochie** [comment]
@duckdegen did you find a resolve for your issue?
