### ISSUE TITLE
iOS firefox browser doesn't deeplink to app

### ISSUE THREAD

**Issue by mpeyfuss** [family/connectkit#210]
**Describe the bug**

On the iOS firefox mobile browser, when I go to connect metamask wallet, I don't get linked to the app or app store but rather just shows that I don't have the extension installed. 

**To reproduce**

ConnectKit version 1.1.3. Try to connect metmask on iOS.

**Expected behavior**

Should get linked to the metamask app

**Screenshots**

**Environment details**

iPhone 13, iOS 16.4.1, firefox mobile version 112

**Additional context**

N/A

**Comment by jonasesr** [comment]
Can confirm this issue. For me it's browser independent.

**Comment by j6i** [comment]
I don't have it personally, but two users have reported it. Both are on Chrome. We use the latest versions of connectkit, wagmi, and viem.

**Comment by lochie** [comment]
This should be resolved with the latest update of ConnectKit where we did an overhaul of these connectors working within browsers that have built-in/extension wallets.

We have also recently have uncovered that MetaMask on iOS requires the WalletConnect Connector to be set up. If you are using the default ConnectKit config then this should work fine (as long as you have included the `walletConnectProjectId`.
