### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Kais3rP** [family/connectkit#220]
**Describe the bug**

wagmi@1.0.1 does not export anymore a `createClient` function but it uses a `createConfig` 

**To reproduce**

connectkit@1.2.3  wagmi@1.0.1

**Comment by lochie** [comment]
we're working on this compatibility, should be out soon

**Comment by lochie** [comment]
This should now be resolved in ConnectKit `1.4.0`
Check out the migration guide: https://docs.family.co/connectkit/migration-guide#section-140-breaking-changes-update-packages
