### ISSUE TITLE
[BUG] Metamask button in connectkit v 1.4.0 is not work well.

### ISSUE THREAD

**Issue by djytwy** [family/connectkit#227]
**Describe the bug**

I already installed metamask wallet in chrome extension but I can't use the metamask connect button.

**To reproduce**
I just try it in connectkit official website. 
First I click connect wallet button then I click metamask button.

https://docs.family.co/connectkit/try-it-out

**Expected behavior**

**Screenshots**

<img width="1243" alt="image" src="https://github.com/family/connectkit/assets/30172796/376685f5-fd45-48aa-9bd9-c6072341674e">

**Environment details**
os: macOS 13.3.1 (22E261)
 browser: chrome 113.0.5672.126 (arm64)

**Additional context**

**Comment by lochie** [comment]
This is a known conflict with Phantom. Something we'll look into eventually.

**Comment by thevenice** [comment]
@lochie Can you please let us know is this issue is fixed yet?

**Comment by volkyeth** [comment]
> This is a known conflict with Phantom. Something we'll look into eventually.

Just for reference for anyone looking into this: v1.5.1 improved Phantom handling, with some gotchas bc of how Phantom hacks around Metamask
https://github.com/family/connectkit/pull/273/files#r1285890486
