### ISSUE TITLE
[BUG] Module '"connectkit"' has no exported member 'getDefaultClient'.ts(2305)

### ISSUE THREAD

**Issue by makeitrein** [family/connectkit#228]
**Describe the bug**

Just bumped to the latest version of connectkit (1.4.0) and it seems like getDefaultClient isn't being exported anymore. Do the docs need a refresh? Thx so much for the wonderful library btw!

<img width="1492" alt="CleanShot 2023-05-25 at 12 02 29@2x" src="https://github.com/family/connectkit/assets/2068463/bff99a81-9d4a-4346-a39c-19103e2efd4c">

Here's my package.json: 

{
  "name": "soulbound-web-ac18",
  "private": true,
  "sideEffects": false,
  "scripts": {
    "build": "run-s build:*",
    "build:css": "npm run generate:css -- --minify",
    "build:remix": "remix build",
    "dev": "run-p dev:*",
    "dev:css": "npm run generate:css -- --watch",
    "dev:remix": "cross-env NODE_ENV=development binode --require ./mocks -- @remix-run/dev:remix dev",
    "format": "prettier --write .",
    "generate:css": "tailwindcss -o ./app/styles/tailwind.css",
    "lint": "eslint --cache --cache-location ./node_modules/.cache/eslint .",
    "seed:build": "tsc --project ./tsconfig.seed.json && tsc-alias -p ./tsconfig.seed.json",
    "setup": "prisma generate && prisma migrate deploy && prisma db seed",
    "start": "remix-serve build",
    "start:mocks": "binode --require ./mocks -- @remix-run/serve:remix-serve build",
    "test": "vitest",
    "test:e2e:dev": "start-server-and-test dev http://localhost:3000 \"npx cypress open\"",
    "pretest:e2e:run": "npm run build",
    "test:e2e:run": "cross-env PORT=8811 start-server-and-test start:mocks http://localhost:8811 \"npx cypress run\"",
    "typecheck": "tsc",
    "validate": "run-p \"test -- --run\" lint typecheck test:e2e:run"
  },
  "prettier": {},
  "eslintIgnore": [
    "/node_modules",
    "/build",
    "/public/build"
  ],
  "packageManager": "pnpm@7.17.0",
  "dependencies": {
    "@emotion/react": "^11.11.0",
    "@emotion/styled": "^11.11.0",
    "@headlessui/react": "^1.7.14",
    "@nivo/bar": "0.80.0",
    "@nivo/core": "0.80.0",
    "@nivo/tooltip": "0.80.0",
    "@prisma/client": "^4.14.1",
    "@remix-run/node": "1.16.1",
    "@remix-run/react": "1.16.1",
    "@remix-run/serve": "^1.16.1",
    "@remix-run/server-runtime": "^1.16.1",
    "@supabase/supabase-js": "^2.22.0",
    "@tanstack/react-query": "^4.29.7",
    "@tanstack/react-table": "^8.9.1",
    "@types/d3-flextree": "^2.1.0",
    "@types/d3-hierarchy": "^3.1.2",
    "@types/d3-timer": "^3.0.0",
    "@types/lodash": "^4.14.194",
    "@uiball/loaders": "^1.2.6",
    "@wagmi/connectors": "^2.0.0",
    "@wagmi/core": "^1.0.6",
    "bcryptjs": "^2.4.3",
    "boring-avatars": "^1.7.0",
    "class-variance-authority": "^0.6.0",
    "clipboard-copy": "^4.0.1",
    "connectkit": "1.4.0",
    "d3-flextree": "^2.1.2",
    "d3-hierarchy": "^3.1.2",
    "d3-timer": "^3.0.1",
    "dayjs": "^1.11.7",
    "ethers": "5.7.2",
    "framer-motion": "^10.12.14",
    "isbot": "^3.6.10",
    "jdenticon": "^3.2.0",
    "lodash": "^4.17.21",
    "lru-cache": "^9.1.1",
    "nft.storage": "^7.1.0",
    "prism-react-renderer": "^2.0.4",
    "prismjs": "^1.29.0",
    "pure-react-carousel": "^1.30.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-edit-text": "^5.1.0",
    "react-hook-form": "^7.43.9",
    "react-jdenticon": "^1.0.1",
    "react-json-tree": "^0.18.0",
    "react-markdown": "6.0.3",
    "reactflow": "^11.7.2",
    "remix-typedjson": "^0.1.7",
    "remix-utils": "^6.3.0",
    "rust_codegen": "^0.2.0",
    "siwe": "^1.1.6",
    "styled-components": "^5.3.10",
    "tabler-icons-react": "^1.56.0",
    "tiny-invariant": "^1.3.1",
    "viem": "^0.3.37",
    "wagmi": "~0.12.12",
    "zod": "^3.21.4",
    "zod-form-data": "^2.0.1"
  },
  "devDependencies": {
    "@faker-js/faker": "^8.0.1",
    "@remix-run/dev": "1.16.1",
    "@remix-run/eslint-config": "1.16.1",
    "@testing-library/cypress": "^9.0.0",
    "@testing-library/dom": "^9.3.0",
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^14.0.0",
    "@testing-library/user-event": "^14.4.3",
    "@types/bcryptjs": "^2.4.2",
    "@types/cookie": "^0.5.1",
    "@types/dagre": "^0.7.48",
    "@types/eslint": "^8.40.0",
    "@types/node": "^20.2.3",
    "@types/react": "^18.2.6",
    "@types/react-dom": "^18.2.4",
    "@types/react-edit-text": "^5.0.1",
    "@types/styled-components": "^5.1.26",
    "@vitejs/plugin-react": "^4.0.0",
    "@vitest/coverage-c8": "^0.31.1",
    "autoprefixer": "^10.4.14",
    "binode": "^1.0.5",
    "c8": "^7.13.0",
    "cookie": "^0.5.0",
    "cross-env": "^7.0.3",
    "cypress": "^12.12.0",
    "eslint": "^8.41.0",
    "eslint-config-prettier": "^8.8.0",
    "eslint-plugin-cypress": "^2.13.3",
    "happy-dom": "^9.20.1",
    "msw": "^1.2.1",
    "npm-run-all": "^4.1.5",
    "postcss": "^8.4.23",
    "prettier": "2.8.8",
    "prettier-plugin-tailwindcss": "^0.3.0",
    "prisma": "^4.14.1",
    "start-server-and-test": "^2.0.0",
    "tailwindcss": "^3.3.2",
    "ts-node": "^10.9.1",
    "tsc-alias": "^1.8.6",
    "tsconfig-paths": "^4.2.0",
    "typescript": "^5.0.4",
    "vite": "^4.3.8",
    "vite-tsconfig-paths": "^4.2.0",
    "vitest": "^0.31.1"
  },
  "engines": {
    "node": ">=14"
  },
  "prisma": {
    "seed": "ts-node --require tsconfig-paths/register prisma/seed.ts"
  }
}

**Comment by lochie** [comment]
ConnectKit version `1.4.0` has some breaking changes to align with the latest version of wagmi (`1.0.0`). 

Check out the migration guide here:
https://docs.family.co/connectkit/migration-guide#section-140-breaking-changes
