### ISSUE TITLE
[BUG] Could not find a declaration file for module 'connectkit'

### ISSUE THREAD

**Issue by lybenson** [family/connectkit#229]
The error was occured when use pnpm install

Could not find a declaration file for module 'connectkit'. '[path]/node_modules/.pnpm/connectkit@1.4.0_react-dom@18.2.0_react-is@16.13.1_react@18.2.0_viem@0.3.37_wagmi@1.0.8/node_modules/connectkit/build/index.es.js' implicitly has an 'any' type.
  There are types at '[path]/node_modules/connectkit/build/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'connectkit' library may need to update its package.json or typings.

**Comment by danielattilasimon** [comment]
I worked around this by disabling [resolvePackageJsonExports](https://www.typescriptlang.org/tsconfig#resolvePackageJsonExports) in tsconfig.json.

**Comment by lochie** [comment]
@lybenson did the above comment resolve this for you?

**Comment by benjitaylor** [comment]
Closing for now re: the above. @lybenson feel free to reopen as a new issue if the problem still persists for you.
