### ISSUE TITLE
[BUG] connectkit@1.3.0 with walletconnect 2.0 configuration errors with EIP712 signing function not available

### ISSUE THREAD

**Issue by TimDaub** [family/connectkit#233]
Basically the issue is the same as here which is that "Missing or invalid "eth_signTypedData_v4"" and so for a user to make it work the next 28 days (lol), you can still just rely on walletconnect 1.0

https://github.com/wagmi-dev/wagmi/discussions/2240#discussioncomment-6051864

**Comment by lekevicius** [comment]
From my experience, WalletConnect 2.0 supports EIP712 (it works when using their w3modal -- you can test), but it seems like this might be related to #35 overall.

**Comment by alex-grover** [comment]
WC2.0 seems to be working for me with Rainbow now. Did not make any dependency updates so maybe something changed on the wallet end?

**Comment by TimDaub** [comment]
dunno, e.g. the wallet I used claims to be WC2 ready but it doesn‘t work. Rainbow does.

**Comment by lochie** [comment]
I believe this is an issue on based on every wallet requiring to implementing this method manually rather than on ConnectKit, elsewise it would be on the peer dependency `wagmi` to implement the function correctly.

Closing this for now since it's not related directly to the ConnectKit library.
