### ISSUE TITLE
[BUG] ConnectKit v.1.4.0 doesn't work with Next.js

### ISSUE THREAD

**Issue by cctdaniel** [family/connectkit#236]
**Describe the bug**

Getting `Module not found: Can't resolve 'fs'` error when running `npm run dev` on a new Next.js project.

**To reproduce**

Follow the ConnectKid docs [getting started guide](https://docs.family.co/connectkit/getting-started).

**Expected behavior**

App should run without any issues.

**Screenshots**

```
Module not found: Can't resolve 'fs'

https://nextjs.org/docs/messages/module-not-found

Import trace for requested module:
./node_modules/node-gyp-build/index.js
./node_modules/bufferutil/index.js
./node_modules/ws/lib/buffer-util.js
./node_modules/ws/lib/websocket.js
./node_modules/ws/index.js
./node_modules/@walletconnect/legacy-client/dist/esm/socket.js
./node_modules/@walletconnect/legacy-client/dist/esm/core.js
./node_modules/@walletconnect/legacy-client/dist/esm/index.js
./node_modules/@walletconnect/legacy-provider/dist/esm/signer.js
./node_modules/@walletconnect/legacy-provider/dist/esm/index.js
./node_modules/@wagmi/connectors/dist/walletConnectLegacy.js
./node_modules/@wagmi/core/dist/connectors/walletConnectLegacy.js
./node_modules/wagmi/dist/connectors/walletConnectLegacy.js
./node_modules/connectkit/build/index.es.js
./src/pages/_app.tsx
```

**Environment details**

MacOS Ventura 13.4 Chrome 113.0.5672.126 (Official Build) (arm64)

**Comment by lochie** [comment]
Seems to be an issue with WalletConnect that doesn't polyfill it's dependency. Check out the resolution here:
https://github.com/family/connectkit/discussions/235#discussioncomment-6081996

**Comment by cctdaniel** [comment]
thank you this works! couldn't find this on connectkit docs, maybe there should be a mention somewhere?
