### ISSUE TITLE
Uncaught Error: No QueryClient set, use QueryClientProvider to set one

### ISSUE THREAD

**Issue by Osub** [family/connectkit#246]
```const root = ReactDOM.createRoot(
    document.getElementById('wallet-login') as HTMLElement
);



root.render(
    <React.StrictMode>
        
            <SIWEProvider
                {...siweConfig}
            >
                <ConnectKitProvider>
                    <App/>
                </ConnectKitProvider>
            </SIWEProvider>
       
    </React.StrictMode>
);
```

**Comment by lochie** [comment]
Thanks for reporting. Could you please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) to help us resolve this issue?

**Comment by benjitaylor** [comment]
Closing for now while awaiting a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example). Feel free to reopen at that time.

**Comment by 18601673727** [comment]
Hello @benjitaylor,
1. Clone https://github.com/family/connectkit/tree/main/examples/nextjs-siwe
2. add `"autoprefixer": "^10.4.18",` `"tailwindcss": "^3.4.1",` to `devDependencies`
3. fill `.env` with proper values
4. `npm run dev`, you'll get the same error

**Comment by 18601673727** [comment]
Also need to change the dependencies as well in order to see the error.

from
```
"connectkit": "workspace:packages/connectkit",
"connectkit-next-siwe": "workspace:packages/connectkit-next-siwe",
```
to
```
"connectkit": "1.7.2",
"connectkit-next-siwe": "0.2.0",
```

**Comment by qidasheng369** [comment]
![image](https://github.com/user-attachments/assets/20175702-3761-4dc4-87af-ca76b47b908e)
 i have same issue. 
 wo just 
 `git clone  https://github.com/family/connectkit.git`
run yarn install and yarn build
then run 
`yarn dev:nextjs-siwe`
then get this issue.

my yarn version is v3.2.3.
my node version is v22.11.0.
and i use registry is https://registry.npmmirror.com/
i don't know where am i wrong.
