### ISSUE TITLE
[BUG]  Connectkit modal stuck on loading wallets from walletConnect on mobile

### ISSUE THREAD

**Issue by sergiycheck** [family/connectkit#248]
**Describe the bug**

Connect kit modal stuck on loading wallets from walletConnect. It seems like pagination is not working correctly and additional walletConnect modal is shown after exit.

**To reproduce**
1. Use chrome on mobile (used iphone 11 chrome)
2. Navigate to [try it out demo](https://docs.family.co/connectkit/try-it-out)
3. click on connect, click on other wallets

**Expected behavior**

All wallets from walletConnect are loaded and paginated, or walletConnect modal is shown after clicking on **other wallets button**

**Screenshots**

https://github.com/family/connectkit/assets/29612247/3502b95b-0a0e-4a1d-a802-a33677b4c719

**Additional context**

I have to click outside of the modal after bg gets a little big darker or on close button to see walletConnect modal.

**Comment by lochie** [comment]
Fixed in https://github.com/family/connectkit/commit/c77dc936ae35834a6c9a0628c4bd26cdff676197, will be pushed to npm soon 👍
