### ISSUE TITLE
[BUG] Metamask and Brave Browser not recognizing plugin 

### ISSUE THREAD

**Issue by 0xM4m4n** [family/connectkit#250]
**Describe the bug**

Use Brave browser. Have Metamask installed and try to connect with metamask option. The screen to install the plugin is displayed. Not sure what to do to troubleshoot this. Similar to this issue as well: https://github.com/family/connectkit/issues/245

**To reproduce**

Using connectkit version 1.4.0 and viem 1.0.7. 

First issue, just cannot connect to metamask.
Have phantom and/or coinbase wallet installed as well. Click the browser wallet (injected) option. The wallets will prompt you to select whether to use their wallets or metamask. Click metamask. Coinbase prompted me first then phantom then an error happened with Maximum callstack exceeded. Reference video below. 

**Expected behavior**

Expected the metamask extension to be recognized but I believe this might be an issue specifically with Brave. On google chrome it works fine with having multiple extensions and connects to metamask. 

**Screenshots**

![image](https://github.com/family/connectkit/assets/107433287/379653e6-ef11-496a-b966-ac5250c6be30)

![image](https://github.com/family/connectkit/assets/107433287/b44101a3-9755-4382-9c85-c89728882f12)

https://github.com/family/connectkit/assets/107433287/42544dfc-70fc-4cde-ae03-27054c1ce79a

**Environment details**

Brave Browser on MacOS M1

**Additional context**

Wondering if there are any suggestions?

**Comment by 0xM4m4n** [comment]
I tried downgrading deps to the versions mentioned in the other issue still same thing

> "viem": "~0.3.19",
> "wagmi": "^1.0.0"

**Comment by caicaishmily** [comment]
I have same problems in my apps

**Comment by 0xjojikun** [comment]
Any updates or workarounds here?  We just bumped all of our dependencies (wagmi, viem, siwe, etc) and upgraded to wallet connect v2.  This is a pretty big bug and is blocking deployment to production.

**Comment by thedonmon** [comment]
Facing the same issue. Not sure there really is a workaround for Brave.

**Comment by lochie** [comment]
This should be resolved with the latest update of ConnectKit where we did an overhaul of these connectors working within browsers that have built-in/extension wallets.
