### ISSUE TITLE
Could not find a declaration file for module 'connectkit'[BUG] 

### ISSUE THREAD

**Issue by g-anwuli** [family/connectkit#254]
**Describe the bug**

I was trying to use component from 'connectkit' in my react typescript app i generated with vite , i kept seeing this error:

Could not find a declaration file for module 'connectkit'. '/Users/macbook/Documents/abc-dx/node_modules/connectkit/build/index.es.js' implicitly has an 'any' type.
  There are types at '/Users/macbook/Documents/abc-dx/node_modules/connectkit/build/index.d.ts', but this result could not be resolved when respecting package.json "exports". The 'connectkit' library may need to update its package.json or typings.ts(7016)

**Comment by 0xRaynor** [comment]
`    "moduleResolution": "node",
` and `    "allowSyntheticDefaultImports": true,
` solved my problem
