### ISSUE TITLE
connectkit v.1.4.0 package.json references mismatching typescript-plugin-styled-components dependency 

### ISSUE THREAD

**Issue by ivyroot** [family/connectkit#262]
https://github.com/family/connectkit/blob/cb287f18344abbfb06bc646ea075951da0976d7a/package.json#L37

In connectkit v1.4.0 the package.json reference  "react": "^18.0.0" as a dev dependency but it also references "typescript-plugin-styled-components": "^2.0.0" as a dev dependency.  Typescript-plugin-styled-components jumps from 2.0.0 to 3.0.0 in the subsequent version.  Version  2.0.0 of typescript plugin-styled-components references  "@types/react": "^16.7.22", as a dev dependency which causes a mismatch when installing.

The exact symptom I saw is as follows, but the issue is about the versioning getting self conflicting due the typescript wrapper package used to get styled-components:

```
├─┬ connectkit 1.4.0
│ ├── ✕ missing peer viem@~0.3.19
│ ├── ✕ unmet peer wagmi@^1.0.0: found 0.12.18
│ └─┬ styled-components 5.3.11
│   ├── ✕ missing peer react-is@">= 16.8.0"
│   └─┬ babel-plugin-styled-components 2.1.4
│     └─┬ @babel/plugin-syntax-jsx 7.22.5
│       └── ✕ missing peer @babel/core@^7.0.0-0
```

**Comment by lochie** [comment]
Thanks for reporting. I don't seem to be able to replicate this, could you provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) for us to review?

**Comment by lochie** [comment]
This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.
