### ISSUE TITLE
Connectkit v1.5 iOS mobile not connecting, Chrome, Safari [BUG] 

### ISSUE THREAD

**Issue by ThomasDEVio** [family/connectkit#274]
**Describe the bug**

Using NextJS + siwe example with latest 1.5v when pressing connect wallet, the MM app opens but doesn't prompt to connect.
Brave works, Chrome, Safari, Twitter in-app browser do not work.

**To reproduce**

Use a recent iOS and latest connectkit + chrome/safari.

**Expected behavior**

Open MM prompt like brave browser does.

**Comment by ThomasDEVio** [comment]
I’ve had many previous versions first 1.4 i think, all have this issue😂and the example always workedthis library is a joke, no one repliesThank you,Thomas


On Mon, 21 Aug 2023 at 10:07 PM Montana wrote:

Same issue, although https://docs.family.co/connectkit/try-it-out does work, maybe that's running an older version?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/family/connectkit/issues/274#issuecomment-1686876271",
"url": "https://github.com/family/connectkit/issues/274#issuecomment-1686876271",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by lochie** [comment]
Based on [another issue that was just self resolved](https://github.com/family/connectkit/issues/279#issuecomment-1689042737) it sounds like you're missing the WalletConnect Project ID.
MetaMask on iOS requires WalletConnect to be configured to work correctly.

Also worth noting that providing a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) helps us reply to issues quicker. Without knowing your configuration we're limited to our availability to help until we resolve another issue that has given more details.
