### ISSUE TITLE
[BUG] Switch Networks tab ui overflow hidden

### ISSUE THREAD

**Issue by wyx2333333** [family/connectkit#277]
**Describe the bug**

in Switch Networks tab, Disconnect button overflow hidden.

**Screenshots**

![13561690256290_ pic](https://github.com/family/connectkit/assets/29940101/104b616b-a861-4627-99b6-ac0ab785becc)
![13571690256311_ pic](https://github.com/family/connectkit/assets/29940101/eed4c571-88dd-4977-8611-9a7433ed0600)
![13581690256318_ pic](https://github.com/family/connectkit/assets/29940101/76c0aae2-9e89-4b65-9086-975de275d777)

**Comment by lochie** [comment]
Good find @wyx2333333, have added a resize trigger to fix this issue
