### ISSUE TITLE
[BUG] Metamask not connecting to my dApp on Mobile (iOS & Android)

### ISSUE THREAD

**Issue by araiczyk-wbi** [family/connectkit#279]
**Describe the bug**

We've been using Connect Kit & Wagmi for a few months in https://playprode.com and it worked like a charm. Yesterday I've been reported that users can't connect their Metamask in mobile phones. I thought maybe you've updated something, so I've installed the latest version of Connect Kit. It still doesn't work. It opens MM but does nothing there, instead of connecting and returning to the dApp like before.

**To reproduce**

[[A CodeSandbox (preferably) or specify which version of ConnectKit you're using along with reproduction steps.](https://codesandbox.io/s/5rhqm0?file=/README.md)](https://codesandbox.io/s/5rhqm0?file=/README.md)

I found this Sandbox from you here: https://github.com/family/connectkit. I've tried in my laptop and it works as expected. Then I've tried it on my phone and has the same behavior described before, it doesn't works. 

**Expected behavior**

Open MM, connect and return to the dApp.

**Screenshots**

**Environment details**

I've tested it both in iOS & Android, Chrome & Safari.

**Additional context**

**Comment by montanaflynn** [comment]
How did you fix this? I'm having same issue on iOS safari. It opens MetaMask but doesn't ask to connect. Also it's localhost if that could be the issue?

**Comment by araiczyk-wbi** [comment]
Hi, I wasn't including the walletConnectProjectId when creating the config.
After that it worked.
Best,

Alejandro

const config = createConfig(

  getDefaultConfig({

    appName: "xx",

    alchemyId: process.env.REACT_APP_ALCHEMYID,

    walletConnectProjectId: process.env.REACT_APP_WALLETCONNECT_PROJECT_ID,

    chains,

  }),

);

**Comment by lochie** [comment]
> Hi, I wasn't including the walletConnectProjectId when creating the config. After that it worked. 

Thanks for that update @araiczyk-wbi, this makes sense as MetaMask on iOS uses the WalletConnect protocol for linking the wallet to the dApp.
