### ISSUE TITLE
[BUG] Connecting on metamask mobile app (iOS) sometimes fails

### ISSUE THREAD

**Issue by pedromcunha** [family/connectkit#28]
**Describe the bug**

Sometimes when connecting (usually after the first successful connect and disconnect) the metamask app returns this error on iOS:

```
{
  "code": -32601,
  "message": "The method wallet_requestPermissions does not exist/is not available"
}
```

**To reproduce**

* Open the connectkit demo app in metamask, try to connect
* Disconnect if successful
* Conncect again if applicable
* The error occurrs

**Expected behavior**

Should always connect on the metamask app

**Screenshots**

**Environment details**

iOS latest version - Metamask version v5.8.1 (986)

**Comment by AustinZhu** [comment]
Same here.

**Comment by tea-juuni** [comment]
I filed an issue against WAGMI, hopefully it gets resolved soon https://github.com/wagmi-dev/wagmi/issues/1365

**Comment by lochie** [comment]
Looks like this issue has been [fixed in wagmi](https://github.com/wagmi-dev/wagmi/pull/1384). Closing this issue for now, thanks for letting us know!
