### ISSUE TITLE
[BUG] FOUC with ChainIcon

### ISSUE THREAD

**Issue by alex-grover** [family/connectkit#282]
**Describe the bug**

The ChainIcon component flashes without the size or radius options applied.

**To reproduce**

ConnectKit 1.5.0 (latest)

https://github.com/alex-grover/connectkit-chain-icon-fouc

**Expected behavior**

The icon renders correctly.

**Screenshots**

https://github.com/family/connectkit/assets/3088615/11914cf8-a65f-4d07-b957-c99278305695

**Environment details**

macOS 14 + Safari 17.0 and Chrome 115.0.5790.170

**Comment by lochie** [comment]
thanks for the report @alex-grover. this will be patched in the next update 🫡
