### ISSUE TITLE
export getDefaultConnectors

### ISSUE THREAD

**Issue by q20274982** [family/connectkit#290]
### Discussed in https://github.com/family/connectkit/discussions/286

<div type='discussions-op-text'>

<sup>Originally posted by **q20274982** August 13, 2023</sup>
When I attempting to provide a custom Connector that extends wagmi's `Connector` to the `createConfig.connectors` within connectkit, [the custom Connector replaces all the defaultConnectors](https://github.com/family/connectkit/blob/e2a9d2d77447143ec58822ced55b1fa66f05be8e/packages/connectkit/src/defaultConfig.ts#L192). Is it feasible to export the getDefaultConnectors function? This way, we could achieve a more flexible integration between the defaultConnectors and the custom Connector</div>

**Comment by lochie** [comment]
Great suggestion, and thanks for the PR! This will make it into the next release 🎉
