### ISSUE TITLE
[BUG] Custom connect button is throwing an error `Cannot read properties of undefined (reading 'name')` on v1.5.x

### ISSUE THREAD

**Issue by lykalabrada** [family/connectkit#294]
**Describe the bug**
Trying to bump our app's connectkit version from `1.4.0` to `1.5.1`, but getting an error with the custom connect button

**To reproduce**
Simple codesandbox with custom connect button:
https://codesandbox.io/s/custom-connect-button-1-5-1-r69w5z

**Expected behavior**
Clicking of Connect Button is expected to work.

**Screenshots**
<img width="618" alt="image" src="https://github.com/family/connectkit/assets/17063281/81e4983f-076a-4835-9a04-fee6ec903608">

**Environment details**
Version 116.0.5845.96 (Official Build) (arm64)

**Additional context**

**Comment by lochie** [comment]
Looks like your missing the [`viem`](https://viem.sh/) dependency in this example. I added `"viem": "1.6.0",` to the package.json and it seems to fix it. Let me know if that fixes your project

**Comment by lykalabrada** [comment]
I added `viem` to the example but getting the same error. In our app we already have `"viem" : "1.6.x"` installed, but still having this issue

**Comment by lochie** [comment]
Looks like there's a missing check when `InjectedConnector` isn't found. Have created a PR to fix this. If you include the `InjectedConnector` in your config's connectors array it will fix this for the time being.
