### ISSUE TITLE
[BUG] DOMException: Failed to execute 'removeChild' on 'Node' after connecting

### ISSUE THREAD

**Issue by polaconovich** [family/connectkit#313]
**Describe the bug**
After accepting connection from Metamask, the page shows an error:
`Application error: a client-side exception has occurred (see the browser console for more information).`
Console says:
`DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.` 

**To reproduce**
- ConnectKit version ^1.5.0, wagmi ~1.1.1
- Using boilerplate ConnectKitButton code from documentation.
- Go to https://criptonita-dev.netlify.app
- Connect with Metamask wallet (Chrome extension)
 
**Expected behavior**
After clicking "Connect" in the Metamask extension from the CDN deployed page, it should render the page.

**Screenshots**
N/A

**Environment details**
- Microsoft Edge Version 118.0.2088.61 (Official build) and Chrome Version 118.0.5993.88 (Official Build)

**Additional context**
- Works as expected when running in dev (localhost:3000) but when deployed to Netlify CDN it gives the error ...

Thank you!

**Comment by lochie** [comment]
I believe this was fixed in a newer version of ConnectKit. Try updating to `1.5.3` and this error should be resolved.

**Comment by polaconovich** [comment]
@lochie thank you, will try today and update the thread

**Comment by polaconovich** [comment]
@lochie upgraded to 1.5.3, same error in Edge and Chrome :(

**Comment by polaconovich** [comment]
package.json:
```
{
  "name": "template",
  "private": true,
  "version": "0.1.0",
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "@headlessui/react": "^1.7.17",
    "@heroicons/react": "^2.0.18",
    "connectkit": "^1.5.3",
    "dotenv": "^16.3.1",
    "next": "^13.5.6",
    "qs": "^6.11.2",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "viem": "~1.0.7",
    "wagmi": "~1.1.1",
    "web3": "^4.2.1"
  },
  "devDependencies": {
    "@types/node": "^18.18.7",
    "@types/qs": "^6.9.9",
    "@types/react": "^18.2.33",
    "autoprefixer": "^10.4.16",
    "eslint": "^8.52.0",
    "eslint-config-next": "^13.5.6",
    "postcss": "^8.4.31",
    "tailwindcss": "^3.3.5",
    "typescript": "^5.2.2"
  }
}
```

**Comment by polaconovich** [comment]
**Update:**
- Tried enclosing the ConnectKit element in div, empty brackets, same error:
```
<div> or <>
      <ConnectKitButton.Custom>
        {({
          isConnected,
          isConnecting,
          show,
          hide,
          address,
          truncatedAddress,
          ensName,
          chain,
        }) => {
          return (
            <button
              onClick={show}
              type='button'
              className='bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-2xl'
            >
              {isConnected ? truncatedAddress : 'Conectare'}
            </button>
          );
        }}
      </ConnectKitButton.Custom>
</div> or </>
```

- Tried changing the language (from es to en) to see if it was that, same error
- Here is a [screencast](https://drive.google.com/file/d/1xQBwfnexZevEmkR6OXSL8iBjot81CWJZ/view?usp=sharing) - Reminder that this only happens when running on CDN (Netlify), on dev env no error!
- This is the code that raises the error:
```
tu.useEffect)(()=>{
                let et = getAppName();
                if (!et || !ed.open)
                    return;
                let en = document.createElement(“meta”);
                return en.setAttribute(“property”, “og:title”),
                en.setAttribute(“content”, et),
                document.head.prepend(en),
                ()=>{
                    document.head.removeChild(en)
                }
            }
 ```
 thanks

**Comment by polaconovich** [comment]
Found the apparent issue. Will post here for anyone else who bump into the same situation:
;tldr;
_Having a wagmi hook (useAccount) in the parent of the component where ConnectKitButton is instantiated causes the error after confirming wallet connection from Metamask, only in production (tested on Netlify and Vercel)._

I have no idea what wagmi does front-end wise, but moving the hook to the same component where ConnectKitButton is instantiated got rid of the error.

Setup that produced the error:
**index.tsx**
```
const Home: NextPage = () => {
  ...
  const { address, isConnected } = useAccount();
  ...
  <Component 
    address={address}
    isConnected={isConnected}
  />
  ...
```
**component.tsx**
```
const Component: React.FC<ComponentProps> = ({address, isConnected}) => {
  ...
  <ConnectKitButton.custom .... />
```

Setup that worked:
**index.tsx**
```
const Home: NextPage = () => {
  ...
  ...
  <Component />
  ...
```
**component.tsx**
```
const Component: React.FC<ComponentProps> = () => {
  const { address, isConnected } = useAccount();
  ...
  <ConnectKitButton.custom .... />
  ...
```

**Comment by lochie** [comment]
Glad you found a resolve @polaconovich! Haven't seen this issue before, sounds like a hydration infinite loop causing the error.

**Comment by albertocevallos** [comment]
Running into the same issue with a similar setup.

I wrote a custom hook that runs `useAccount` and `useNetwork` in my Header component, where my `ConnectKitButton` resides.

Would be nice to get a fix a from the connectkit team. I suspect many others devs are using wagmi hooks in the same component as the `ConnectKitButton` .

<img width="1204" alt="Screen Shot 2023-11-07 at 6 40 13 PM" src="https://github.com/family/connectkit/assets/27132021/ecedb640-b467-432d-beb2-6efa2a399fd9">
