### ISSUE TITLE
[BUG] Release 1.5.3 Package path . is not exported from package

### ISSUE THREAD

**Issue by ghTravis** [family/connectkit#325]
**Describe the bug**

When using 1.5.3 I get the following error when trying to use webpack:
```
Module not found: Error: Package path . is not exported from package /path/to/node_modules/connectkit (see exports field in /path/to/node_modules/connectkit/package.json)
```

**To reproduce**

Use 1.5.2, error does not exist. Upgrade to 1.5.3, error above is present

**Expected behavior**

Webpack should be able to find the module.

**Environment details**

Using WSL Ubuntu, webpack to pack all js modules

**Additional info**

I'm not sure what else to include. I had been pulling my hair out trying to figure out what this error means for a few hours. I then just tried downgrading to 1.5.2 and the error went away and my app was able to load again.

**Comment by lochie** [comment]
Does this issue still persist in [`1.6.0`](https://family.co/changelog/2024-01-10)? Upgrading from `1.5.2` to `1.6.0` has no breaking changes so should just work.

**Comment by lochie** [comment]
Closing this issue as this should be resolved in newer versions of ConnectKit.
