### ISSUE TITLE
[BUG] Error with "export *" in a Client Boundary in Next.js Project Using wagmi

### ISSUE THREAD

**Issue by ThomasJ0nes** [family/connectkit#333]
**I encountered a build error in my Next.js 14 project when trying to use the wagmi package. The error occurs during the build process and seems to be related to how modules are exported in wagmi.**

### Steps to Reproduce
1. Create a new Next.js project or use an existing one.
2. Install the wagmi package using npm or yarn. -` npm install connectkit wagmi@1.x viem@1.x`
3. Import and use wagmi in any component or page in the Next.js project. I was following step3 of the getting started docs 
4. add additional config to nextjs config specified in docs -
 ```
module.exports = {
  webpack: (config) => {
    config.resolve.fallback = { fs: false, net: false, tls: false };
    return config;
  },
};
```
5.  Run the development server or build the project.

### Expected Behavior
The Next.js project should compile without errors, and wagmi should be usable within the project.

### Actual Behavior
When attempting to compile the project, the following error is encountered:
![image](https://github.com/family/connectkit/assets/94535525/f5985856-2a74-4e81-ab04-5bb5c9ddb7c0)

This error suggests an incompatibility issue with how the wagmi package exports modules and how Next.js handles these exports in its client-side code.

### Possible Cause
This issue might be related to the way wagmi is exporting its modules (potentially using export * syntax) and how this pattern is not compatible with Next.js's module handling, especially in a server-side rendering (SSR) context.

**Comment by Aryan9592** [comment]
@ThomasJ0nes try adding 'use client' where you implemented the code of 3rd step. This solved the error in my case, and it will probably work for you too if there ain't any unwanted error or bug in your code!

**Comment by Aryan9592** [comment]
>Still a bit annoying that i have to declare `use client` at my app initialization but it works so.

Sadly, yeah

@ThomasJ0nes But I am facing some other error whenever I try to select the option `other wallets` on my frontend

![Screenshot 2024-01-16 174714](https://github.com/family/connectkit/assets/88618913/2ac80574-d522-456b-87f7-ece70e6c345d)

**Comment by ThomasJ0nes** [comment]
@Aryan9592 ye i had this issue as well found a fix for this make you env variables NEXT_PUBLIC like this:

`NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID=`
`NEXT_PUBLIC_ALCHEMY_ID`


Only issue is it makes you keys public to the client but for the sake of the hackathon which i guess you're probably in its fine as its Connect Kits issue as the `use client`  workaround at app init prevents you from getting env variables that are not client side. Once that issue is fixed where you don't need to have to declare use client at app init this error would be fixed.

**Comment by Aryan9592** [comment]
Thanks @ThomasJ0nes 
Wasn't knowing `NEXT_PUBLIC` would be such a big deal to make it work..and am not participating in any kind of hackathon, was just trying out this library

**Comment by lochie** [comment]
> @Aryan9592 ye this a good work around and resolved it
> 
> Still a bit annoying that i have to declare `use client` at my app initialization but it works so.

Going to close this issue as it seems to be resolved.

For future reference we've added some information in the Getting Started documentation to help people avoid this issue:
https://docs.family.co/connectkit/getting-started#getting-started-nextjs-app-router
