### ISSUE TITLE
ConnectKit breaks with wagmi version ^2.x

### ISSUE THREAD

**Issue by Nazeeh21** [family/connectkit#336]
**Describe the bug**
i am using wagmi version `^2.2.1` and viem version `2.x`
but I am getting this error 

```shell
Module not found: Package path ./providers/alchemy is not exported from package /Users/nazeeh/code/GhoPay/node_modules/.pnpm/connectkit@1.6.0_@babel+core@7.23.7_react-dom@18.2.0_react-is@18.2.0_react@18.2.0_typescript@_wxe6jyuce3js77cjrlbd2qvosy/node_modules/wagmi (see exports field in /Users/nazeeh/code/GhoPay/node_modules/.pnpm/connectkit@1.6.0_@babel+core@7.23.7_react-dom@18.2.0_react-is@18.2.0_react@18.2.0_typescript@_wxe6jyuce3js77cjrlbd2qvosy/node_modules/wagmi/package.json)

```

In the docs, it is guiding to install wagmi version `1.x` and veim version `1.x`. So I think it is not yet compatible with wagmi and viem versions `2.x`. This issue also continues with wagmi's `createConfig` as mentioned in #333.

**To reproduce**

A CodeSandbox (preferably) or specify which version of ConnectKit you're using along with reproduction steps.
I am using connectkit version `^1.6.0`

**Expected behavior**

It should work with the latest versions of wagmi and viem

**Screenshots**

<img width="1508" alt="image" src="https://github.com/family/connectkit/assets/56908732/cb28c275-4859-492f-8ac2-4278fc1834c7">

**Environment details**

If applicable, let us know which OS, browser, browser version etc you're using.

**Additional context**

If I downgrade my wagmi and viem versions to `^1.x`, then it works

**Comment by chaoticsoooul** [comment]
Encountered the same issue

**Comment by brianjckim** [comment]
+1, ran into the same issue

**Comment by lochie** [comment]
Working on it! Check out progress here: https://github.com/family/connectkit/pull/332

**Comment by MiltonTulli** [comment]
Hi @lochie. Thanks for your work here! Is it possible that `connectkit-next-siwe` is not working with connectkit `1.7.x` and wagmi `2.x`

**Comment by lochie** [comment]
@MiltonTulli what issue are you seeing exactly? could you open an issue with more details?
