### ISSUE TITLE
[BUG] Not able to view coinbase QR when i click on the new UI modal  

### ISSUE THREAD

**Issue by ayepRahman** [family/connectkit#34]
**Describe the bug**

Iam using connectkit 0.02, the connect modal has different UI and iam not able to see coinbase QR code when i click on it. Not sure if this is a bug though. Below are the 2 diff UI

![Screenshot 2022-10-24 at 12 24 08 PM](https://user-images.githubusercontent.com/26382836/197448244-63216183-abff-44dd-ae76-497de247dac8.png)

![Screenshot 2022-10-24 at 12 24 18 PM](https://user-images.githubusercontent.com/26382836/197448242-38295658-3000-4746-91f4-9e542d543f1f.png)

**Comment by lochie** [comment]
Hey @ayepRahman, this would be the mobile view you're looking at, which uses the mobile connector code which doesn't open the Coinbase Wallet QR code (it's expecting to open the CBW app on a mobile device).

If you are spoofing a mobile user agent in your dev tools that would cause the mobile view appearing, if not could you give us more details on how to reproduce this issue?

**Comment by ayepRahman** [comment]
Hey @lochie, this is desktop view. Iam working on a nextjs app.

Here my config


```
import { getDefaultClient } from "connectkit";
import { chain, createClient } from "wagmi";

const ALCHEMY_ID = process.env.NEXT_PUBLIC_ALCHEMY_API_ID || "";

export const wagmiClient = createClient(
  getDefaultClient({
    appName: "some app name",
    alchemyId: ALCHEMY_ID,
    chains: [chain.mainnet, chain.goerli, chain.hardhat],
  })
);
```

and on _app.tsx

```
import { ChakraProvider } from "@chakra-ui/react";
import { wagmiClient } from "config/wagmi";
import { ConnectKitProvider } from "connectkit";
import type { AppProps } from "next/app";
import { theme } from "styles";
import { WagmiConfig } from "wagmi";

const MyApp = ({ Component, pageProps }: AppProps) => {
  return (
    <WagmiConfig client={wagmiClient}>
      <ConnectKitProvider>
        <ChakraProvider theme={theme}>
          <Component {...pageProps} />
        </ChakraProvider>
      </ConnectKitProvider>
    </WagmiConfig>
  );
};

export default MyApp;
```

**Comment by ayepRahman** [comment]
@lochie - thanks for the sharing, look like you're right seem like iam spooking a mobile user agent in my dev tool.
