### ISSUE TITLE
[BUG] No ENS resolution for dApps not supporting mainnet

### ISSUE THREAD

**Issue by SonOfMosiah** [family/connectkit#350]
**Describe the bug**

There is not ENS resolution when mainnet is excluded from the wagmi chains variable.

**To reproduce**

Version 1.7.1

Easily reproducible by observing ConnectKitButton behavior when chains array includes mainnet and when it excludes mainnet.

examples: chains: [base, mainnet] vs chains: [base]

**Expected behavior**

Since the current behavior is to resolve ENS regardless of the user's connected chain, it would be expected to resolve ENS regardless of the dApp's supported chains.

**Comment by philogicae** [comment]
I had the same issue, this is a "normal" behavior also present in WalletConnect for some reasons. I have the fix, so I will push a PR and hopefully it will be fine 😁
