### ISSUE TITLE
[BUG] Infinite spinner when loading "More"

### ISSUE THREAD

**Issue by vpontis** [family/connectkit#359]
The mobile "More" button should open a Wallet Connect modal but instead it does an infinite "More" spinner. 

![IMG_31D45BB28210-1](https://github.com/family/connectkit/assets/1319079/acdf2c94-34db-4247-8232-9530d3e6e095)

**Comment by lochie** [comment]
Nice spot @vpontis, have made a fix for this and should be available in the next version of ConnectKit.
