### ISSUE TITLE
[BUG] showAvatar attribute does not exist in options

### ISSUE THREAD

**Issue by Pszz** [family/connectkit#361]
**Describe the bug**

 "connectkit": "^1.7.2"
 "node": "v18.17.0"

```typescript
import { ConnectKitProvider } from 'connectkit'

 <ConnectKitProvider options={{ showAvatar: false }}>
   {children}
 </ConnectKitProvider>
```

Prompt "showAvatar" attribute does not exist.
I've tried repeatedly uninstalling and installing "connectkit", to no real effect.

**Comment by lochie** [comment]
Sorry this is due to misguided documentation. `showAvatar` is supported on the [ConnectButton](https://docs.family.co/connectkit/api-reference#connectkitbutton) rather than on the provider itself. The docs have now been updated to reflect this.
Thanks for letting us know about this issue!
