### ISSUE TITLE
[BUG] Wallet fails to reconnect after disconnection

### ISSUE THREAD

**Issue by ddickson** [family/connectkit#362]
**Describe the bug**

On the demo page (https://docs.family.co/connectkit/try-it-out), cannot reconnect to the page with a WalletConnect wallet after a successful disconnection.

**To reproduce**
1. Connect a WalletConnect wallet (i.e. Rainbow) to the demo page at https://docs.family.co/connectkit/try-it-out 
2. Disconnect the wallet
3. Attempt to reconnect the wallet again, which fails. The QR code is read by the WalletConnect wallet, but is not able to complete the connection to the demo page. The only way to reconnect is to hard refresh the demo page. 

**Expected behavior**

Successful reconnection to the demo page after disconnection

**Environment details**

I'm using the latest version of the Rainbow app on iOS on the demo page. In my own development environment Coinbase Wallet also fails the reconnection exercise. Metamask (injected wallet) reconnects fine. 

**Additional context**

Using ConnectKit 1.7.2

**Comment by lochie** [comment]
nice catch @ddickson, there's a fix in #363 that will be released soon

**Comment by lochie** [comment]
This feature is now available in ConnectKit `1.7.3` 🫡
