### ISSUE TITLE
[BUG] Switching to not set up chain

### ISSUE THREAD

**Issue by alagunoff** [family/connectkit#367]
**Describe the bug**

Switching to the chain doesn't work if it is not set up in the wallet

**To reproduce**

1. Have DefiChain EVM Testnet set up in wagmi config but not in the wallet
2. Visit the app using another chain not set up in the wagmi config and wallet
3. Try to switch to DefiChain EVM Testnet

**Expected behavior**

Prompt to add DefiChain EVM Testnet network to the wallet first and then switch to it

**Screenshots**

![image](https://github.com/family/connectkit/assets/46949445/abec7580-241c-4fec-b0b9-bdf5bfba7e26)
![image](https://github.com/family/connectkit/assets/46949445/0f2f90bb-4001-4e87-a744-2125414a8500)

**Environment details**

- Windows 11
- Chrome Version 122.0.6261.129 (Official Build) (64-bit)
- Node 20.11.1

**Comment by lochie** [comment]
This would either be an issue with the wallet not implementing `eth_addEthereumChain`, or [wagmi](https://github.com/wagmi-dev/wagmi)'s handling of this RPC method. Going to close this issue as it's not relating to the ConnectKit library.
