### ISSUE TITLE
[BUG] Connector Deeplinks are not working

### ISSUE THREAD

**Issue by eduardopelitti** [family/connectkit#379]
**Describe the bug**

When using a connector that requires Deeplinks to trigger connection requests to desktop apps, it always shows the QR code.

**To reproduce**

Choose any connector that requires deeplinks to work (e.g.: Zerion), but in our case we patched the library to support the Bloom Wallet, a desktop wallet.

**Expected behavior**

When choosing a connector that requires deeplinks to work, it should open the deeplink.

**Screenshots**

![Screenshot 2024-04-29 at 12 45 46](https://github.com/family/connectkit/assets/3876078/05642ec1-8b5c-463c-8926-2beda1f2ca89)
![Screenshot 2024-04-29 at 12 45 49](https://github.com/family/connectkit/assets/3876078/3bf8e624-e867-4e44-a9c5-0835679e74b9)

**Environment details**

Browser: Brave, Safari, Chrome.

**Additional context**

The issue appears to be in the following file: 

https://github.com/family/connectkit/blob/main/packages/connectkit/src/components/Common/ConnectorList/index.tsx, in these lines:

```
let deeplink =
    !wallet.isInstalled && isMobile
      ? wallet.getWalletConnectDeeplink?.(uri ?? '')
      : undefined;

  const redirectToMoreWallets = isMobile && isWalletConnectConnector(wallet.id);
  if (redirectToMoreWallets) deeplink = undefined; // mobile redirects to more wallets page

  return (
    <ConnectorButton
      type="button"
      as={deeplink ? 'a' : undefined}
      href={deeplink ? deeplink : undefined}
      disabled={context.route !== routes.CONNECTORS}
      onClick={
        deeplink
          ? undefined
          : () => {
              if (redirectToMoreWallets) {
                context.setRoute(routes.MOBILECONNECTORS);
              } else {
                context.setRoute(routes.CONNECT);
                context.setConnector({ id: wallet.id });
              }
            }
      }
    >
```
    
Notice that the logic conditions for `deeplink` will never be met on a real scenario:

```
    let deeplink =
    !wallet.isInstalled && isMobile
      ? wallet.getWalletConnectDeeplink?.(uri ?? '')
      : undefined;
     
```
      
So a user with the installed library and using the dApp from desktop, will never use the deeplink, necessary to open the connection request in the Wallet.

Changing these conditions to just `wallet.isInstalled` makes the deep links work properly, but I'm not sure how it affects the rest of the cases that you're handling there.

We can work on a PR to solve this, but would need some additional guidance.

------
Additional context from the original issue: 

https://github.com/family/connectkit/pull/353#issuecomment-2083229149

Special thanks to @MarkNerdi from the Bloom team for helping out and pointing us in the right direction.

**Comment by aschenkel** [comment]
Hi guys,

as mentioned on @eduardopelitti opening comment, the issue can be found on this line https://github.com/family/connectkit/blob/main/packages/connectkit/src/components/Common/ConnectorList/index.tsx#L91
and it seems like we need a property to identify when a DESKTOP wallet needs to open a deep link.

When `isMobile` is `false`, there are cases where we still need to use the `deeplink` for a small group of desktop wallets. (without messing up with browser connectors such as MM).

I couldn't find a prop inside the `wallet` object that could be used for this.
@lochie are you familiar with an existing property that could be used for this case? 

if that's not the case, I think adding a new property on the `walletConfigs` for an app that needs to open a deep link on desktop its needed

**Comment by lochie** [comment]
@aschenkel sounds like this could become more complicated if there's a wallet that has both desktop deeplinking and also requiring a QR code option, which at that point they should probably be doing a PR to `wagmi` to include their own connector.

it does indeed sound like we need a new property here to flag if it should deeplink for desktop. it could be `shouldDeeplinkDesktop` or something similar.

would you have a list of some of these wallets that require this support? i'd love to test their current UX.

**Comment by aschenkel** [comment]
Right now the only wallet that is not working and needs this fix is `ledgerLive`.

There is also an [open PR](https://github.com/family/connectkit/pull/353) for supporting Bloom wallet which needs this fix as well.

I've just created a PR that address this https://github.com/family/connectkit/pull/392
