### ISSUE TITLE
[BUG]  - Updating `customTheme` prop on ConnectKitProvider won't update the color unless `key` prop is changed but then all the application loses it state

### ISSUE THREAD

**Issue by 0x33dm** [family/connectkit#382]
**Describe the bug**

1. changing "customTheme" won't change the theme of the pop "Connect Wallet"

````ts

const theme = useTheme()

<ConnectKitProvider customTheme={ theme === 'dark' ? darkWalletTheme : lightWalletTheme }>
....
````

2. If we set the "key" prop on the ConnectKitProvider and switch theme, then the pop up will switch theme.

**_BUT..._**

_When changing the "key" value on <ConnectKitProvider> **_all the application state stored on useEffect will return to their defaults_**. For instance, all fields  populated with useEffect will re-render and lose their data ( i.e. a field that has a string inside of it will become blank )._

````ts

const theme = useTheme()

<ConnectKitProvider 
  key={theme} // <- this makes the theme reload and the pop for Connect does open with the right theme

  customTheme={ theme === 'dark' ? darkWalletTheme : lightWalletTheme }>
....
````

**To reproduce**

ConnectKit: 1.7.3
We use [next-themes](https://github.com/pacocoursey/next-themes) to manage our theme ( that shouldn't matter tough )

Unfortunately I don't have a CodeSandBox at the moment as it's a bit complicated to extra this code from our application now, but would be happy to provide one if you can't replicate

**Expected behavior**

Changing the "customTheme" prop on <ConnectKit> would be enough to change the theme on the pop-up without having to pass a new "key" value to <ConnectKit> resulting in the problem with the state.

**Environment details**

chrome, next.js 14

**Comment by 0x69sudo** [comment]
Spoke with the team. Will be fixed in upcoming release.

**Comment by 0x33dm** [comment]
Actually i realised the right way of doing it, on our theme object.

```ts

  const { resolvedTheme } = useTheme()
  const { setCustomTheme } = useContext(Context)!

  const customTheme =
    resolvedTheme === 'dark'
      ? darkWalletTheme
      : resolvedTheme === 'pro'
        ? proWalletTheme
        : lightWalletTheme

  useEffect(() => {
    setCustomTheme(customTheme)
  }, [resolvedTheme, setCustomTheme, customTheme])
```
