### ISSUE TITLE
Not able to set `shimDisconnect` on metamask connector

### ISSUE THREAD

**Issue by 0x33dm** [family/connectkit#411]
**Describe the bug**

Many users expect Metamask to simply "reconnect" if you click "reconnect" without having to have a op up asking for reconnection.

For that to happen we would need to set `shimDisconnect` to false as described [on wagmi docs](https://wagmi.sh/core/api/connectors/injected) but i can't find a way of changing the config using the API.

**To reproduce**

Disconnect and Connect again, the pop up will appear and ask for reconnecting.

**Expected behavior**

Default metamask behaviour: to simply reconnect without having the pop up open again

**Comment by lochie** [comment]
@0x33dm we opted for the default `shimDisconnect: true` as we want the UX to remain the same for each wallet, and didn't want it to be changeable within the default configuration. though there are ways to get around this by creating your own wagmi config and not using our `getDefaultConfig` setup.

you're welcome to open a PR for this feature and we can start a discussion with the community to see if this is something majority of people want.

**Comment by 0x33dm** [comment]
> @0x33dm we opted for the default `shimDisconnect: true` as we want the UX to remain the same for each wallet, and didn't want it to be changeable within the default configuration. though there are ways to get around this by creating your own wagmi config and not using our `getDefaultConfig` setup.

is there a place with an example of how to do this in order to change the value of shimDisconnect ?

> you're welcome to open a PR for this feature and we can start a discussion with the community to see if this is something majority of people want.

thank you
