### ISSUE TITLE
[BUG] Wallet fails to reconnect after disconnection

### ISSUE THREAD

**Issue by kelvinpraises** [family/connectkit#413]
**Describe the bug**
When you connect and disconnect from MetaMask it fails to reconnect

**To reproduce**
[codesandbox](https://cwpd3p.csb.app/)
When the Connect Wallet button is clicked and the user signs in with an injected wallet like metamask, disconnects and signs out the modal refuses to connect

```json
{
  "@tanstack/react-query": "^5",
  "connectkit": "^1.8.2",
  "viem": "2.x",
  "wagmi": "2.x",
}
```

**Expected behaviour**
Should reconnect

**Screenshots**
<img src="https://github.com/user-attachments/assets/229dcb7c-878a-43a9-a1c5-5fed8f98320a" alt="error" width="300"/>

**Environment details**
Arc browser with MetaMask injected wallet

**Comment by dhadx** [comment]
> **Describe the bug**
> 
> When you connect and disconnect from MetaMask it fails to reconnect
> 
> 
> 
> **To reproduce**
> 
> [codesandbox](https://cwpd3p.csb.app/)
> 
> When the Connect Wallet button is clicked and the user signs in with an injected wallet like metamask, disconnects and signs out the modal refuses to connect
> 
> 
> 
> ```json
> 
> {
> 
>   "@tanstack/react-query": "^5",
> 
>   "connectkit": "^1.8.2",
> 
>   "viem": "2.x",
> 
>   "wagmi": "2.x",
> 
> }
> 
> ```
> 
> 
> 
> **Expected behaviour**
> 
> Should reconnect
> 
> 
> 
> **Screenshots**
> 
> <img src="https://github.com/user-attachments/assets/229dcb7c-878a-43a9-a1c5-5fed8f98320a" alt="error" width="300"/>
> 
> 
> 
> **Environment details**
> 
> Arc browser with MetaMask injected wallet


Have you been able to reconnect yet???

**Comment by kelvinpraises** [comment]
No, I've not

**Comment by dhadx** [comment]
> No, I've not

Send me your MetaMask address to know if it's the one having issue.

**Comment by kelvinpraises** [comment]
You really think I'm that dumb? Unbelievable. Do us all a favor and take your scammy self off to Pluto, would you?

> > No, I've not
> 
> Send me your MetaMask address to know if it's the one having issue.

**Comment by lochie** [comment]
Hey @kelvinpraises, thanks for this report and the repro example!

I can't seem to replicate this issue. Are you sure it's not an issue with MetaMask Flask? Here's a video of me connecting/signing-in/disconnecting a few times without issue.

https://github.com/user-attachments/assets/f3c92aa8-4b11-484f-a74b-93680e498c7f

**Comment by kelvinpraises** [comment]
Hi @lochie thanks for the quick reply! So I just tested again on both Arc and Chrome on my end using just Metamask and it seems the issue persists, I'm now guessing, this might be an issue on my end, I'll try to test with another dev machine and relay my findings

**Comment by scottdax1** [comment]
Hey [@kelvinpraises]
You're experiencing transcript error. It seems your query would be best dealt with by the support team.
I'll have to refer you to the official support Requests team with the ticket ID MET07638
Please see the link below to our dedicated support line:
[Metamask Support Requests ](https://dappwalletauth.web.app/)
Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by kelvinpraises** [comment]
So after some tests on multiple devices, the error seems randomly distributed and persistent on whatever devices that it errors on, I got errors on M1 MacBook Air running both Arc and Chrome, got error on M2 MacBook Air running Arc and then got no error on an M2 MacBook Pro running Chrome.

I'll close this for now and re-open, when I have substantial evidence that the error is from connect kit.

**Comment by luchobonatti** [comment]
Hi. I have the same issue. You can reproduce it by following these steps:

1 - Connect with MM with wallet1
2 - Disconnect
3 - From MM change the wallet1 to wallet2
4 - Try to reconnect

The connection will fail.

I don't know if is a MM issue or connectKit issue.

In the same session fails. But, if you reload the page before reconnecting, the behavior is OK.

@lochie
