### ISSUE TITLE
[BUG] Breaks with Dynamic Import

### ISSUE THREAD

**Issue by jethroguce** [family/connectkit#42]
**Describe the bug**

Breaks with Next@13.0.2 

**To reproduce**

(https://codesandbox.io/s/connectkit-nextjs-typescript-forked-6zj2o7)

**Expected behavior**

Should load Properly

**Screenshots**

![Screen Shot 2022-11-11 at 10 33 46 AM](https://user-images.githubusercontent.com/4945428/201250169-b0bcb309-079b-4a38-ad1f-cfe3aa019092.png)

**Comment by lochie** [comment]
Hey @jethroguce, 

ConnectKit hasn't yet been updated to work perfectly with the latest wagmi `0.8.x` release just yet (it released yesterday). They've [dropped support for CommonJS modules](https://wagmi.sh/docs/migration-guide#commonjs-support-dropped), which is something we need to update here. We're hoping to get this update out asap.

I suggest downgrading wagmi to `0.7.15` (the last release before `0.8.x`) until we have that update ready.

**Comment by lochie** [comment]
Hey @jethroguce,

Apologies that this took some time, we had to rework a few things to get the module into a pure ES module.
We've just released ConnectKit version `1.1.0` which now supports wagmi `0.8.x` which should resolve this problem 🙌

Thanks for reporting the issue, we appreciate the contribution!
