### ISSUE TITLE
[BUG] Keep forcing me to Goerli network

### ISSUE THREAD

**Issue by 70nyIT** [family/connectkit#44]
**Describe the bug**

Forced switch network even if the network is correctly configured among the supported ones.

**To reproduce**

https://codesandbox.io/s/bw14lu?file=/src/App.tsx

**Expected behavior**

To connect Metamask and not seeing the "Switch Network" window appear, as I'm already connected to a Supported Network

**Screenshots**

![image](https://user-images.githubusercontent.com/12898752/201783706-ff4321a5-66ce-4e10-9851-223593f33bfa.png)

**Environment details**

Currently using:
- Ubuntu 22.04 (tested also on MacOS)
- Brave v 1.45.118 (Chromium 107.0.5304.91)
- connectkit v. 1.0.0

**Additional context**

If I'm connected to Goerli network, when I ask to "connect", it connects with no problem.
When I'm connected to Polygon Mainnet (that's among the supported chains, if you see my CodeSandbox), it asks me to switch to Goerli. If I don't do that, it refuses to connect the wallet.

**Comment by metabacalhau** [comment]
The behaviour has to do with this [line](https://github.com/family/connectkit/blob/0415976ee03f216bf70acdeef7b1cfc19907b25a/packages/connectkit/src/components/ConnectModal/ConnectWithInjector/index.tsx#L179) so I guess as a workaround you can prioritise one of the networks as follows `<ConnectKitProvider options={{ initialChainId: chain.goerli.id }}>`

**Comment by lochie** [comment]
We've released an update in [ConnectKit `1.1.2`](https://github.com/family/connectkit/releases/tag/v1.1.2) where if you set the [`initialChainId` to `0`](https://docs.family.co/connectkit/api-reference#ConnectKitProvider-initialChainId) it will no longer target a chain and let the wallet connect to whichever chain it was previously set to.

Hopefully this helps resolve some issues 🙏

**Comment by AdamK222** [comment]
Thanks, it's fixed

**Comment by 70nyIT** [comment]
Thanks

**Comment by nneverlander** [comment]
this worked for me too

> We've released an update in [ConnectKit `1.1.2`](https://github.com/family/connectkit/releases/tag/v1.1.2) where if you set the [`initialChainId` to `0`](https://docs.family.co/connectkit/api-reference#ConnectKitProvider-initialChainId) it will no longer target a chain and let the wallet connect to whichever chain it was previously set to.
> 
> Hopefully this helps resolve some issues 🙏
