### ISSUE TITLE
[BUG] `SIWEConfig` and `SIWEContext` are not exported

### ISSUE THREAD

**Issue by samkingco** [family/connectkit#51]
**Describe the bug**

I'm trying to implement my own custom sign in button using `next-auth`.

When I configure the `SIWEProvider`, I have to import the `SIWEConfig` from `"connectkit/build/components/Standard/SIWE/SIWEContext"` because it's not available from `connectkit`.

Same issue with the actual React context too. I'm trying to follow the `SIWEButton` component, and use context to correctly create the message and sign in, but the context that I _can_ import returns a module not found error.

**To reproduce**

```typescript
// SignInEthButton.tsx

// Have to import from here since `SIWEContext` isn't available from `connectkit`
import { SIWEContext } from "connectkit/build/components/Standard/SIWE/SIWEContext";
import { useContext } from "react";

export function SignInEthButton() {
  // Fails since `SIWEContext` cannot be found
  const siweContext = useContext(SIWEContext);
  
  // Rest of button logic similar to `SIWEButton` from connectkit
}
```

Results in the following error:
```
./src/components/ui/SignInEthButton.tsx:1:0
Module not found: Can't resolve 'connectkit/build/components/Standard/SIWE/SIWEContext'
> 1 | import { SIWEContext } from "connectkit/build/components/Standard/SIWE/SIWEContext";
```

**Expected behavior**

To be able to import the context so that I can make my own sign in button.

Alternatively expose an easy way to call `signIn`, or to open the sign in section of the modal from another component.

**Screenshots**

N/A

**Environment details**

Using:
- `next@12.3.1`
- `connectkit@^1.0.0`
- `wagmi@0.7.15`
- `siwe@1.1.6`

**Additional context**

My use case is basically because I don't want to prompt the user to sign a message as soon as they connect their wallet. I want them to only have to sign a message when it's necessary for a certain part of my app. I set the `enabled` flag to false on the SIWE provider (which is also kind of weird to me, I would expect something like `signInOnConnect`), which means I need a SIWE button. I don't want to have to reskin the connectkit component, and would rather provide my own underlying `Button` component. Happy to rebuild my own, but it's hard when you don't have access to the same context.

**Comment by lochie** [comment]
A new update to SIWE has just been released, check out the [release notes](https://github.com/family/connectkit/releases/tag/v1.2.0) to learn more. This should hopefully resolve this issue ☺️
