### ISSUE TITLE
[BUG] Unable to modify customTheme 

### ISSUE THREAD

**Issue by brennanfife** [family/connectkit#57]
I seem to be unable to modify certain variables (such as  '--ck-border-radius' or '--ck-connectbutton-border-radius').

**Comment by brennanfife** [comment]
I created a simple example repo [here](https://github.com/brennanfife/connectkit-custom-theme-bug) (I was unable to get Codesandbox properly working). Notice how I have the customTheme passed into the ConnectKitProvider.

**Comment by brennanfife** [comment]
Any updates?

**Comment by lochie** [comment]
Hey @brennanfife, from what I'm seeing this appears to be working if you use strings for each value. We're looking at making the custom theming more robust in the near future so it can handle things a bit smarter as right now it's implemented in a way we're not 100% settled just yet.
Sorry that this caused some confusion!
