### ISSUE TITLE
[BUG] SIWE: Missing environment variable: SESSION_SECRET

### ISSUE THREAD

**Issue by neocho** [family/connectkit#58]
I'm getting a Missing environment variable: SESSION_SECRET. 
I have a .env file in the base directory with SESSION_SECRET set and also set it directly within configureSIWE.

<img width="957" alt="Screen Shot 2022-12-06 at 4 54 56 PM" src="https://user-images.githubusercontent.com/32602764/206061206-d95ec2ff-a136-47df-87b4-e21449d3f445.png">

**Comment by markibanez** [comment]
I was able to fix this by passing an empty string if `SESSION_SECRET` is `undefined` as it is when run on client-side. 

```
import { configureSIWE } from 'connectkit-next-siwe';

export const siwe = configureSIWE({
    apiRoutePrefix: '/api/siwe',
    session: {
        password: process.env.SESSION_SECRET || '',
        cookieOptions: {
            secure: process.env.VERCEL_ENV === 'production',
            sameSite: 'strict'
        }
    }
});
```

As a sidenote, I don't think anyone should resolve/fix this bug by exposing the session secret to the client by prepending the variable with `NEXT_PUBLIC`. I feel that the session secret is meant to be accessed only in the backend.

**Comment by lochie** [comment]
Hey everyone, just letting you know that we have [a PR](https://github.com/family/connectkit/pull/69) that's waiting approval that should fix the current SIWE issues we've been seeing. This should be in the next major release of ConnectKit. ☺️

**Comment by lochie** [comment]
A new update to SIWE has just been released, check out the [release notes](https://github.com/family/connectkit/releases/tag/v1.2.0) to learn more. This should hopefully resolve this issue ☺️
