### ISSUE TITLE
[BUG] Importing breaks on wagmi ^0.9

### ISSUE THREAD

**Issue by adreesdev** [family/connectkit#60]
Connect kit not working with wagmi 0.9. It shows the following error.

X [ERROR] No matching export in "node_modules/wagmi/dist/index.js" for import "chain"

    node_modules/connectkit/build/index.es.js:1:7:
      1 │ import{chain as e,configureChains as o,useNetwork as n,useSwitchNetwork as t,useConnect as r,useEnsAddress as i,useEnsName a...
        ╵        ~~~~~

However it does work with wagmi 0.8

**Comment by m3tamorphTECH** [comment]
following

**Comment by lochie** [comment]
Fixed in ConnectKit version `1.1.1`, thanks for letting us know!
https://github.com/family/connectkit/releases/tag/v1.1.1
