### ISSUE TITLE
[BUG] Conditional custom theme doesn't work

### ISSUE THREAD

**Issue by hffxx** [family/connectkit#62]
I want to have two custom themes depending on dark/light mode. After changing mode, theme doesn't change. Right theme is applied after page refresh

**Comment by lochie** [comment]
Custom Theme Variables are still an experimental feature of ConnectKit. We currently don't support theme mode switching with Custom Themes Variables but this is definitely something we'll be looking into right away when we start extending out this API.

For a temporary solution @META-DREAMER discovered a fairly simple workaround: https://github.com/family/connectkit/discussions/67#discussioncomment-4404773

**Comment by lochie** [comment]
I've started [a discussion](https://github.com/family/connectkit/discussions/77) as this isn't a bug, but rather a feature suggestion.
