### ISSUE TITLE
[BUG] SIWE not working

### ISSUE THREAD

**Issue by SimonHausdorf** [family/connectkit#71]
**Describe the bug**

Added SIWE as described in the docs but I am receiving the following two errors:
```
Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check your code at main.jsx:41.
```

```
The above error occurred in the <$a> component:
```

**To reproduce**

https://codesandbox.io/s/pedantic-mestorf-k4flof?file=/src/main.jsx

**Expected behavior**

Button to connect to wallet should show.

I think it would also be good to have SIWE in the example packages.

**Comment by lochie** [comment]
Hey @SimonHausdorf just letting you know that we have [a PR](https://github.com/family/connectkit/pull/69) that's waiting approval that should fix the current SIWE issues we've been seeing. This should be in the next major release of ConnectKit. ☺️

**Comment by lochie** [comment]
A new update to SIWE has just been released, check out the [release notes](https://github.com/family/connectkit/releases/tag/v1.2.0) to learn more. This should hopefully resolve this issue ☺️
