### ISSUE TITLE
[BUG] ENS Name Does Not Populate Connect Kit Button

### ISSUE THREAD

**Issue by raparri01** [family/connectkit#74]
**Describe the bug**

After I connect my wallet to my dApp, I can see that the wallet is connected and I can see the wallet balance, but the ENS name associated with my wallet does not appear in the button. Additionally, I don't see any ENS name fetch in the "Recent Requests" section of my Alchemy dashboard. The same behavior occurs on the public wagmi provider.

**To reproduce**

Dependencies:
connectkit: ^1.1.0
wagmi: ^0.10.4

CodeSandbox: https://codesandbox.io/s/great-wood-z90onq?file=/src/App.js

Connect wallet with ENS name associated and ConnectKitButton text.

**Expected behavior**

I expect the wallets associated ENS name to appear in place of the truncated address. This bug does not occur on the family.co docs examples.

**Environment details**

Node version: 16.16.0

**Comment by lochie** [comment]
@raparri01 it look like your codesandbox example isn't using the `AlchemyProvider` at all.
Here are some links that might help implementing this correctly:
- Check out the[ wagmi docs to see how to implement the AlchemyProvider with an Alchemy API key](https://wagmi.sh/react/providers/alchemy#apikey).
- Check out [this example in our docs](https://docs.family.co/connectkit/getting-started#getting-started-2-implementation) to see how we suggest implementing providers using our client helper.

**Comment by raparri01** [comment]
I didn't change anything but this started working weirdly. Something probably changed on the alchemy node I was using. Marking as closed.
