### ISSUE TITLE
[BUG] Ethhub is sunset / links are dead

### ISSUE THREAD

**Issue by gakonst** [family/connectkit#75]
**Describe the bug**

The link https://docs.ethhub.io/using-ethereum/wallets/intro-to-ethereum-wallets encountered in the "Learn More" flow of ConnectKit are broken per Ethhub's sunset on Dec 8th: https://twitter.com/econoar/status/1600932091398529024?s=20&t=HXNXsQVO5EgAENb65JdAAQ

![image](https://user-images.githubusercontent.com/17802178/211218268-b5f556d1-5e97-421e-baa5-9e83425746dc.png)

**Comment by lochie** [comment]
Thanks for the heads up on this @gakonst!

I've made a PR (https://github.com/family/connectkit/pull/76) to fix this, and also added options to replace these links easily if developers wish to provide link to their own about wallets/ethereum onboarding pages.

**Comment by gakonst** [comment]
ACK - thanks for the quick turnaround!

**Comment by lochie** [comment]
Hey @gakonst, just a quick update, this has been pushed up in the [latest release](https://github.com/family/connectkit/releases/tag/v1.1.2) of ConnectKit (1.1.2).
Thanks again for letting us know 😊

**Comment by gakonst** [comment]
gg thanks!
