### ISSUE TITLE
[BUG] "Approve in Wallet" text in Switch Networks modal overlaps Network name

### ISSUE THREAD

**Issue by eduardopelitti** [family/connectkit#78]
**Describe the bug**

The issue happens in the Switch Networks modal, which contains the list of supported networks and prompts the user to change to one of these instead of the selected network in the Wallet client (i.e.: Metamask).

If the user presses one of the networks, in order to change to a supported network, a label with the text "Approve in Wallet" is displayed next to the name of the network when the Metamask prompt opens. When this happens, there may be an overlap between the "Approve in Wallet" text and the network name, depending on its length, and probably the language the user is in.

In this particular case reproduced in the screenshots, the client is in English, the network name is Fantom Testnet, and the overlap exists.

Please note that in a base use case, with officially supported network such as Ethereum (homestead) or Goerli this doesn't happen, since the length of the name doesn't allow the bug to emerge, at least in English.

**To reproduce**

Using version 1.1.1, add Fantom Testnet as one of the supported networks when initializing the wagmi client with the following code:

```
{
    id: 4002,
    name: 'Fantom Testnet',
    network: 'Fantom Testnet',
    rpcUrls: {
      default: {
        http: ['https://xapi.testnet.fantom.network/lachesis'],
      },
    },
    nativeCurrency: {
      decimals: 18,
      name: 'Fantom',
      symbol: 'FTM',
    },
    testnet: true,
  }
```

Or the custom chain declaration for version 1.0.1:

```
{
    id: 4002,
    name: 'Fantom Testnet',
    network: 'Fantom Testnet',
    rpcUrls: { default: 'https://xapi.testnet.fantom.network/lachesis' },
    nativeCurrency: {
      decimals: 18,
      name: 'Fantom',
      symbol: 'FTM',
    },
    testnet: true,
  }
```

Then open your application, connect your wallet on a supported network and switch to an unsupported network, i.e.: one that is not present in the `configureChains` function call. This will trigger the Switch Networks modal from Connect Kit. With the modal open, press the Fantom Testnet option from the options list, and notice that the "Approve in wallet" legend appears (in English localization), overlapping the network name.

**Expected behavior**

Texts should not overlap, the length of the network should not collide with the Approve in Wallet label.

**Screenshots**

![Screen Shot 2023-01-11 at 16 31 56](https://user-images.githubusercontent.com/3876078/211900599-61ae5e4d-386c-470a-ad6d-f1379ac5067c.png)

**Environment details**

Brave Browser, latest version, running with `connectkit 1.1.1` and also tested in `connectkit 1.0.1` (same issue).

**Additional context**

Nothing else.

**Comment by lochie** [comment]
Good catch @eduardopelitti, I'll have a look into cleaning this up. 😊

**Comment by lochie** [comment]
A simple solve for this was to hide this text on this particular view due there being no limit to how long a chain name can be. We've kept the highlighted background and the spinner animation, so hopefully that keeps things coherent ✨

Thanks again for pointing this out!
