### ISSUE TITLE
[BUG] TypeError: n.replaceAll is not a function

### ISSUE THREAD

**Issue by vanthao03596** [family/connectkit#83]
**Describe the bug**

When i create project with [create-wagmi](https://github.com/wagmi-dev/create-wagmi) and connectkit. I got  n.replaceAll is not a function after run npm run dev

**To reproduce**

connectkit 1.1.1

**Expected behavior**

Project run without problem

**Environment details**

BR: chrome
OS: Ubuntu 20.04

**Comment by vanthao03596** [comment]
Everything work find after upgrade to nodejs 15

**Comment by lochie** [comment]
@vanthao03596 sounds like you found a fix, going to close this now. Thanks!
