### ISSUE TITLE
[BUG] Cannot import module react/jsx-runtime

### ISSUE THREAD

**Issue by wojtekwtf** [family/connectkit#96]
Hey, I love your work! We want to use connectkit in our app, but encountered the following problem

**Describe the bug**

After a fresh install, connectkit crashes the app with:

```
Server Error
Error: Cannot find module .../node_modules/react/jsx-runtime imported from .../node_modules/connectkit/build/index.es.js.
Did you mean to import react/isx-runtime.is?
```

**To reproduce**

I guess install connectkit via yarn and see if it works for next.js 12 and react 17?
I totally expect this to be related to our environment but I don't know where to start the investigation

**Expected behavior**

I'd expect connectkit not to crash right after the installation 😄 

**Screenshots**

<img width="1306" alt="Screenshot 2023-01-27 at 13 51 27" src="https://user-images.githubusercontent.com/10712818/215092825-7dfab233-0191-4fbd-bb5a-6650148a8b13.png">

**Environment details**
```
"next": "12.0.8"
"react": "17.0.2"
```

**Additional context**

When i manually change
`import { jsx as L, jsxs as _, Fragment as F } from "react/jsx-runtime`
to
`import { jsx as L, jsxs as _, Fragment as F } from "react/jsx-runtime.js`
in
`node_modules/connectkit/build/index.es.js`

it works as expected

Any suggestions here? We're open to updating dependencies / navigating stuff that may not work on our end

**Comment by nneverlander** [comment]
same problem - freshly installed connectkit

**Comment by lochie** [comment]
@wojtekwtf does this error still occur if you downgrade to ConnectKit version `1.1.1`? If so, could you set up a codesandbox with a reproducible example?

Also I've opened PR https://github.com/family/connectkit/pull/94 which will resolve a few issues with our build process that had affected version `1.1.2`, which might be affecting this import issue you're having. I'm just waiting on some internal reviews before moving forward

**Comment by wojtekwtf** [comment]
@lochie thanks for getting back!

to my knowledge, we first encountered this still on `1.1.1` and only just updated to `1.1.2`, still with the same error.

i'll be able to put it on codesandbox later this week

**Comment by lochie** [comment]
@wojtekwtf I've just discovered an issue with compatibility with wagmi `0.10.12`, can you try downgrading wagmi to `0.10.11` and see if that solves this problem?

**Comment by olaf89** [comment]
I have the same problem. Downgrading does not help.

```
Module not found: Error: Can't resolve 'react/jsx-runtime' in 'node_modules/connectkit/build'
Did you mean 'jsx-runtime.js'?
BREAKING CHANGE: The request 'react/jsx-runtime' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
```

**Comment by lochie** [comment]
without a reproducible example this is a bit hard to debug, currently it looks like it's best to update to react `18` and typescript `4.9.4`

from some short research you may need to change some items in your `tsconfig` relating to the `"jsx": "react-jsx"` option.
