### ISSUE TITLE
Could not resolve "ethers/lib/utils.js" in React vite

### ISSUE THREAD

**Issue by starc007** [family/connectkit#97]
Getting Error Could not resolve "ethers/lib/utils.js" in React vite.
Version:-
connectkit @1.1.2
wagmi @0.11.0
react @18.2.0 

<img width="979" alt="image" src="https://user-images.githubusercontent.com/36479565/215209433-f04f8b92-1413-4cb3-95fc-c24d3cd6ccb5.png">

**Comment by shubhamsaxena-devslane** [comment]
Just checking with you here. You need ethers as well, did you install that as well?
If not, use `yarn add ethers` or `npm install ethers`

**Comment by lochie** [comment]
hey @starc007 can you confirm that you've installed `ethers`? thanks ☺️

**Comment by starc007** [comment]
yes, ethers was installed...

**Comment by kremalicious** [comment]
for now, you need to downgrade to `ethers@5`. More context: https://github.com/wagmi-dev/wagmi/issues/1785

**Comment by lochie** [comment]
@kremalicious is correct, wagmi hasn't included support for ethers v6 yet so we require v5.
our [peer dependency](https://github.com/family/connectkit/blob/d04aabce36f0b95d057cd3f54075d8d948e3ae22/packages/connectkit/package.json#L49) config should have thrown an error for you on install, but this may have been easily missed.

we've also recently [updated the docs](https://docs.family.co/connectkit/getting-started) to reflect this with the following for the install script:
`npm install connectkit wagmi ethers@^5`
