### ISSUE TITLE
[BUG] Coinbase Wallet not getting disconnected on localhost when disconnecting from wallet itself (v1.1..2)

### ISSUE THREAD

**Issue by shubhamsaxena-devslane** [family/connectkit#99]
**Describe the bug**

When I try to disconnect the wallet from the coinbase wallet extension, it is not reflected in the app until the page is refreshed while using localhost (Vite Server). Note: In the production build it is working as expected.

**Code**

main.tsx
```
import { ConnectKitProvider, getDefaultClient } from "connectkit";
import { WagmiConfig, createClient } from "wagmi";
import { mainnet, polygon, polygonMumbai } from "wagmi/chains";

const client = createClient(
	getDefaultClient({
		appName: "ConnectKit Vite demo",
		infuraId: APP_INFURA_ID,
		autoConnect: true,
		chains: [mainnet, polygon, polygonMumbai],
	})
);

const root = ReactDOM.createRoot(
	document.getElementById("root") as HTMLElement
);

root.render(
	<WagmiConfig client={client}>
		<ConnectKitProvider theme="auto">
			<App />
		</ConnectKitProvider>
	</WagmiConfig>
);
```

**To reproduce**

1. Connect to Coinbase Wallet
2. Disconnect from the wallet using the extension

**Expected behavior**

1. The wallet should be disconnected from the app as well.

**Screenshots**

https://user-images.githubusercontent.com/111336675/215312636-60267838-b107-4145-b835-7fe27af40abb.mp4

**Environment details and dependencies**

OS: Windows 11 
Vite: 3.1.0
React: 18.2.0
ConnectKit: 1.1.2
Ethers: 5.7.2
Wagmi: 0.10.15

**Comment by lochie** [comment]
Hey @shubhamsaxena-devslane, I'm unable to replicate this issue. Does this issue also occur for you on the [wagmi examples](https://wagmi.sh/examples/connect-wallet) page? If so then it's possibly an issue with the Coinbase Wallet injector and we'll need to file an issue with them.

**Comment by shubhamsaxena-devslane** [comment]
Hey @lochie , thanks for replying back. And yes, you were correct. It is also happening on the wagmi example page you mentioned.

**Comment by lochie** [comment]
Okay cool, good to know. We're looking to talk with the CBW team soon to resolve some other issues we've been seeing, so I'll be sure to bring this up as well.

Thanks for letting us know, we're always appreciating the contribution 😊

**Comment by lochie** [comment]
Since this is also occuring over on the wagmi this would be better to open on the [wagmi references repo](https://github.com/wagmi-dev/references) as it's not an issue with ConnectKit.
